import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsChatList = [
  const Icon(MoonIconsChat.chat16),
  const Icon(MoonIconsChat.chat24),
  const Icon(MoonIconsChat.chat32),
  const Icon(MoonIconsChat.comment_add16),
  const Icon(MoonIconsChat.comment_add24),
  const Icon(MoonIconsChat.comment_add32),
  const Icon(MoonIconsChat.comment_bubble_alert16),
  const Icon(MoonIconsChat.comment_bubble_alert24),
  const Icon(MoonIconsChat.comment_bubble_alert32),
  const Icon(MoonIconsChat.comment_bubble_question_mark16),
  const Icon(MoonIconsChat.comment_bubble_question_mark24),
  const Icon(MoonIconsChat.comment_bubble_question_mark32),
  const Icon(MoonIconsChat.comment_bubble16),
  const Icon(MoonIconsChat.comment_bubble24),
  const Icon(MoonIconsChat.comment_bubble32),
  const Icon(MoonIconsChat.comment_remove16),
  const Icon(MoonIconsChat.comment_remove24),
  const Icon(MoonIconsChat.comment_remove32),
  const Icon(MoonIconsChat.comment_text16),
  const Icon(MoonIconsChat.comment_text24),
  const Icon(MoonIconsChat.comment_text32),
  const Icon(MoonIconsChat.comment16),
  const Icon(MoonIconsChat.comment24),
  const Icon(MoonIconsChat.comment32),
  const Icon(MoonIconsChat.double_bubble16),
  const Icon(MoonIconsChat.double_bubble24),
  const Icon(MoonIconsChat.double_bubble32),
  const Icon(MoonIconsChat.stats_chat16),
  const Icon(MoonIconsChat.stats_chat24),
  const Icon(MoonIconsChat.stats_chat32),
];

final List<String> iconsChatNameList = [
  "chat16",
  "chat24",
  "chat32",
  "comment_add16",
  "comment_add24",
  "comment_add32",
  "comment_bubble_alert16",
  "comment_bubble_alert24",
  "comment_bubble_alert32",
  "comment_bubble_question_mark16",
  "comment_bubble_question_mark24",
  "comment_bubble_question_mark32",
  "comment_bubble16",
  "comment_bubble24",
  "comment_bubble32",
  "comment_remove16",
  "comment_remove24",
  "comment_remove32",
  "comment_text16",
  "comment_text24",
  "comment_text32",
  "comment16",
  "comment24",
  "comment32",
  "double_bubble16",
  "double_bubble24",
  "double_bubble32",
  "stats_chat16",
  "stats_chat24",
  "stats_chat32",
];
