import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsDevicesList = [
  const Icon(MoonIconsDevices.bluetooth16),
  const Icon(MoonIconsDevices.bluetooth24),
  const Icon(MoonIconsDevices.bluetooth32),
  const Icon(MoonIconsDevices.joystick16),
  const Icon(MoonIconsDevices.joystick24),
  const Icon(MoonIconsDevices.joystick32),
  const Icon(MoonIconsDevices.keyboard16),
  const Icon(MoonIconsDevices.keyboard24),
  const Icon(MoonIconsDevices.keyboard32),
  const Icon(MoonIconsDevices.mac16),
  const Icon(MoonIconsDevices.mac24),
  const Icon(MoonIconsDevices.mac32),
  const Icon(MoonIconsDevices.macbook_and_iphone16),
  const Icon(MoonIconsDevices.macbook_and_iphone24),
  const Icon(MoonIconsDevices.macbook_and_iphone32),
  const Icon(MoonIconsDevices.macbook16),
  const Icon(MoonIconsDevices.macbook24),
  const Icon(MoonIconsDevices.macbook32),
  const Icon(MoonIconsDevices.mouse16),
  const Icon(MoonIconsDevices.mouse24),
  const Icon(MoonIconsDevices.mouse32),
  const Icon(MoonIconsDevices.phone16),
  const Icon(MoonIconsDevices.phone24),
  const Icon(MoonIconsDevices.phone32),
  const Icon(MoonIconsDevices.smartphone16),
  const Icon(MoonIconsDevices.smartphone24),
  const Icon(MoonIconsDevices.smartphone32),
  const Icon(MoonIconsDevices.tv_box16),
  const Icon(MoonIconsDevices.tv_box24),
  const Icon(MoonIconsDevices.tv_box32),
];

final List<String> iconsDevicesNameList = [
  "bluetooth16",
  "bluetooth24",
  "bluetooth32",
  "joystick16",
  "joystick24",
  "joystick32",
  "keyboard16",
  "keyboard24",
  "keyboard32",
  "mac16",
  "mac24",
  "mac32",
  "macbook_and_iphone16",
  "macbook_and_iphone24",
  "macbook_and_iphone32",
  "macbook16",
  "macbook24",
  "macbook32",
  "mouse16",
  "mouse24",
  "mouse32",
  "phone16",
  "phone24",
  "phone32",
  "smartphone16",
  "smartphone24",
  "smartphone32",
  "tv_box16",
  "tv_box24",
  "tv_box32",
];
