import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsShopList = [
  const Icon(MoonIconsShop.bag16),
  const Icon(MoonIconsShop.bag24),
  const Icon(MoonIconsShop.bag32),
  const Icon(MoonIconsShop.bank16),
  const Icon(MoonIconsShop.bank24),
  const Icon(MoonIconsShop.bank32),
  const Icon(MoonIconsShop.basket16),
  const Icon(MoonIconsShop.basket24),
  const Icon(MoonIconsShop.basket32),
  const Icon(MoonIconsShop.buy_crypto16),
  const Icon(MoonIconsShop.buy_crypto24),
  const Icon(MoonIconsShop.buy_crypto32),
  const Icon(MoonIconsShop.card16),
  const Icon(MoonIconsShop.card24),
  const Icon(MoonIconsShop.card32),
  const Icon(MoonIconsShop.cart16),
  const Icon(MoonIconsShop.cart24),
  const Icon(MoonIconsShop.cart32),
  const Icon(MoonIconsShop.coins16),
  const Icon(MoonIconsShop.coins24),
  const Icon(MoonIconsShop.coins32),
  const Icon(MoonIconsShop.crypto_coin16),
  const Icon(MoonIconsShop.crypto_coin24),
  const Icon(MoonIconsShop.crypto_coin32),
  const Icon(MoonIconsShop.crypto16),
  const Icon(MoonIconsShop.crypto24),
  const Icon(MoonIconsShop.crypto32),
  const Icon(MoonIconsShop.wallet16),
  const Icon(MoonIconsShop.wallet24),
  const Icon(MoonIconsShop.wallet32),
  const Icon(MoonIconsShop.wireless_pay16),
  const Icon(MoonIconsShop.wireless_pay24),
  const Icon(MoonIconsShop.wireless_pay32),
];

final List<String> iconsShopNameList = [
  "bag16",
  "bag24",
  "bag32",
  "bank16",
  "bank24",
  "bank32",
  "basket16",
  "basket24",
  "basket32",
  "buy_crypto16",
  "buy_crypto24",
  "buy_crypto32",
  "card16",
  "card24",
  "card32",
  "cart16",
  "cart24",
  "cart32",
  "coins16",
  "coins24",
  "coins32",
  "crypto_coin16",
  "crypto_coin24",
  "crypto_coin32",
  "crypto16",
  "crypto24",
  "crypto32",
  "wallet16",
  "wallet24",
  "wallet32",
  "wireless_pay16",
  "wireless_pay24",
  "wireless_pay32",
];
