import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsChartsList = [
  const Icon(MoonIconsCharts.area16),
  const Icon(MoonIconsCharts.area24),
  const Icon(MoonIconsCharts.area32),
  const Icon(MoonIconsCharts.bar_alternative16),
  const Icon(MoonIconsCharts.bar_alternative24),
  const Icon(MoonIconsCharts.bar_alternative32),
  const Icon(MoonIconsCharts.bar_vertical16),
  const Icon(MoonIconsCharts.bar_vertical24),
  const Icon(MoonIconsCharts.bar_vertical32),
  const Icon(MoonIconsCharts.bar16),
  const Icon(MoonIconsCharts.bar24),
  const Icon(MoonIconsCharts.bar32),
  const Icon(MoonIconsCharts.dashboard16),
  const Icon(MoonIconsCharts.dashboard24),
  const Icon(MoonIconsCharts.dashboard32),
  const Icon(MoonIconsCharts.fin16),
  const Icon(MoonIconsCharts.fin24),
  const Icon(MoonIconsCharts.fin32),
  const Icon(MoonIconsCharts.line16),
  const Icon(MoonIconsCharts.line24),
  const Icon(MoonIconsCharts.line32),
  const Icon(MoonIconsCharts.pie_chart16),
  const Icon(MoonIconsCharts.pie_chart24),
  const Icon(MoonIconsCharts.pie_chart32),
  const Icon(MoonIconsCharts.relation16),
  const Icon(MoonIconsCharts.relation24),
  const Icon(MoonIconsCharts.relation32),
  const Icon(MoonIconsCharts.round16),
  const Icon(MoonIconsCharts.round24),
  const Icon(MoonIconsCharts.round32),
];

final List<String> iconsChartsNameList = [
  "area16",
  "area24",
  "area32",
  "bar_alternative16",
  "bar_alternative24",
  "bar_alternative32",
  "bar_vertical16",
  "bar_vertical24",
  "bar_vertical32",
  "bar16",
  "bar24",
  "bar32",
  "dashboard16",
  "dashboard24",
  "dashboard32",
  "fin16",
  "fin24",
  "fin32",
  "line16",
  "line24",
  "line32",
  "pie_chart16",
  "pie_chart24",
  "pie_chart32",
  "relation16",
  "relation24",
  "relation32",
  "round16",
  "round24",
  "round32",
];
