import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsMailList = [
  const Icon(MoonIconsMail.box16),
  const Icon(MoonIconsMail.box24),
  const Icon(MoonIconsMail.box32),
  const Icon(MoonIconsMail.email_stats16),
  const Icon(MoonIconsMail.email_stats24),
  const Icon(MoonIconsMail.email_stats32),
  const Icon(MoonIconsMail.envelope16),
  const Icon(MoonIconsMail.envelope24),
  const Icon(MoonIconsMail.envelope32),
  const Icon(MoonIconsMail.filter_crossed16),
  const Icon(MoonIconsMail.filter_crossed24),
  const Icon(MoonIconsMail.filter_crossed32),
  const Icon(MoonIconsMail.filter16),
  const Icon(MoonIconsMail.filter24),
  const Icon(MoonIconsMail.filter32),
  const Icon(MoonIconsMail.flag16),
  const Icon(MoonIconsMail.flag24),
  const Icon(MoonIconsMail.flag32),
  const Icon(MoonIconsMail.link16),
  const Icon(MoonIconsMail.link24),
  const Icon(MoonIconsMail.link32),
  const Icon(MoonIconsMail.send_right16),
  const Icon(MoonIconsMail.send_right24),
  const Icon(MoonIconsMail.send_right32),
  const Icon(MoonIconsMail.send16),
  const Icon(MoonIconsMail.send24),
  const Icon(MoonIconsMail.send32),
];

final List<String> iconsMailNameList = [
  "box16",
  "box24",
  "box32",
  "email_stats16",
  "email_stats24",
  "email_stats32",
  "envelope16",
  "envelope24",
  "envelope32",
  "filter_crossed16",
  "filter_crossed24",
  "filter_crossed32",
  "filter16",
  "filter24",
  "filter32",
  "flag16",
  "flag24",
  "flag32",
  "link16",
  "link24",
  "link32",
  "send_right16",
  "send_right24",
  "send_right32",
  "send16",
  "send24",
  "send32",
];
