import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsSecurityList = [
  const Icon(MoonIconsSecurity.bet_insurance16),
  const Icon(MoonIconsSecurity.bet_insurance24),
  const Icon(MoonIconsSecurity.bet_insurance32),
  const Icon(MoonIconsSecurity.key16),
  const Icon(MoonIconsSecurity.key24),
  const Icon(MoonIconsSecurity.key32),
  const Icon(MoonIconsSecurity.lock16),
  const Icon(MoonIconsSecurity.lock24),
  const Icon(MoonIconsSecurity.lock32),
  const Icon(MoonIconsSecurity.magnet16),
  const Icon(MoonIconsSecurity.magnet24),
  const Icon(MoonIconsSecurity.magnet32),
  const Icon(MoonIconsSecurity.passport_alert16),
  const Icon(MoonIconsSecurity.passport_alert24),
  const Icon(MoonIconsSecurity.passport_alert32),
  const Icon(MoonIconsSecurity.passport16),
  const Icon(MoonIconsSecurity.passport24),
  const Icon(MoonIconsSecurity.passport32),
  const Icon(MoonIconsSecurity.qr_code_alternative16),
  const Icon(MoonIconsSecurity.qr_code_alternative24),
  const Icon(MoonIconsSecurity.qr_code_alternative32),
  const Icon(MoonIconsSecurity.qr_code16),
  const Icon(MoonIconsSecurity.qr_code24),
  const Icon(MoonIconsSecurity.qr_code32),
  const Icon(MoonIconsSecurity.security_attention16),
  const Icon(MoonIconsSecurity.security_attention24),
  const Icon(MoonIconsSecurity.security_attention32),
  const Icon(MoonIconsSecurity.shield_secured16),
  const Icon(MoonIconsSecurity.shield_secured24),
  const Icon(MoonIconsSecurity.shield_secured32),
  const Icon(MoonIconsSecurity.shield16),
  const Icon(MoonIconsSecurity.shield24),
  const Icon(MoonIconsSecurity.shield32),
  const Icon(MoonIconsSecurity.umbrella16),
  const Icon(MoonIconsSecurity.umbrella24),
  const Icon(MoonIconsSecurity.umbrella32),
  const Icon(MoonIconsSecurity.unlock16),
  const Icon(MoonIconsSecurity.unlock24),
  const Icon(MoonIconsSecurity.unlock32),
  const Icon(MoonIconsSecurity.verified_face16),
  const Icon(MoonIconsSecurity.verified_face24),
  const Icon(MoonIconsSecurity.verified_face32),
  const Icon(MoonIconsSecurity.verified16),
  const Icon(MoonIconsSecurity.verified24),
  const Icon(MoonIconsSecurity.verified32),
];

final List<String> iconsSecurityNameList = [
  "bet_insurance16",
  "bet_insurance24",
  "bet_insurance32",
  "key16",
  "key24",
  "key32",
  "lock16",
  "lock24",
  "lock32",
  "magnet16",
  "magnet24",
  "magnet32",
  "passport_alert16",
  "passport_alert24",
  "passport_alert32",
  "passport16",
  "passport24",
  "passport32",
  "qr_code_alternative16",
  "qr_code_alternative24",
  "qr_code_alternative32",
  "qr_code16",
  "qr_code24",
  "qr_code32",
  "security_attention16",
  "security_attention24",
  "security_attention32",
  "shield_secured16",
  "shield_secured24",
  "shield_secured32",
  "shield16",
  "shield24",
  "shield32",
  "umbrella16",
  "umbrella24",
  "umbrella32",
  "unlock16",
  "unlock24",
  "unlock32",
  "verified_face16",
  "verified_face24",
  "verified_face32",
  "verified16",
  "verified24",
  "verified32",
];
