import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsSportsList = [
  const Icon(MoonIconsSports.afl),
  const Icon(MoonIconsSports.american_football),
  const Icon(MoonIconsSports.archery),
  const Icon(MoonIconsSports.athletics),
  const Icon(MoonIconsSports.audl),
  const Icon(MoonIconsSports.badminton),
  const Icon(MoonIconsSports.baseball),
  const Icon(MoonIconsSports.basketball),
  const Icon(MoonIconsSports.beach_volleyball),
  const Icon(MoonIconsSports.biathlon),
  const Icon(MoonIconsSports.bombay),
  const Icon(MoonIconsSports.bowls),
  const Icon(MoonIconsSports.boxing),
  const Icon(MoonIconsSports.call_of_duty),
  const Icon(MoonIconsSports.canoeing),
  const Icon(MoonIconsSports.car_racing),
  const Icon(MoonIconsSports.casino),
  const Icon(MoonIconsSports.chess),
  const Icon(MoonIconsSports.cricket),
  const Icon(MoonIconsSports.cross_country),
  const Icon(MoonIconsSports.cs_go),
  const Icon(MoonIconsSports.curling),
  const Icon(MoonIconsSports.cycling),
  const Icon(MoonIconsSports.darts),
  const Icon(MoonIconsSports.diving),
  const Icon(MoonIconsSports.dota_2),
  const Icon(MoonIconsSports.e_ice_hockey),
  const Icon(MoonIconsSports.e_nba),
  const Icon(MoonIconsSports.e_soccer),
  const Icon(MoonIconsSports.equestrian),
  const Icon(MoonIconsSports.esport_generic),
  const Icon(MoonIconsSports.featured),
  const Icon(MoonIconsSports.fencing),
  const Icon(MoonIconsSports.field_hockey),
  const Icon(MoonIconsSports.floorball),
  const Icon(MoonIconsSports.formula_1),
  const Icon(MoonIconsSports.formula_e),
  const Icon(MoonIconsSports.futsal),
  const Icon(MoonIconsSports.gaelic_hurling),
  const Icon(MoonIconsSports.golf),
  const Icon(MoonIconsSports.greyhound),
  const Icon(MoonIconsSports.gymnastics),
  const Icon(MoonIconsSports.handball),
  const Icon(MoonIconsSports.harness),
  const Icon(MoonIconsSports.horse_racing),
  const Icon(MoonIconsSports.ice_hockey),
  const Icon(MoonIconsSports.indy_racing),
  const Icon(MoonIconsSports.judo),
  const Icon(MoonIconsSports.kabaddi),
  const Icon(MoonIconsSports.king_of_glory),
  const Icon(MoonIconsSports.lacrosse),
  const Icon(MoonIconsSports.lol),
  const Icon(MoonIconsSports.mma),
  const Icon(MoonIconsSports.motor),
  const Icon(MoonIconsSports.motorcycle_racing),
  const Icon(MoonIconsSports.nordic_combined),
  const Icon(MoonIconsSports.olympics),
  const Icon(MoonIconsSports.overwatch),
  const Icon(MoonIconsSports.rainbow_six),
  const Icon(MoonIconsSports.rocket_league),
  const Icon(MoonIconsSports.rowing),
  const Icon(MoonIconsSports.rugby),
  const Icon(MoonIconsSports.sailing),
  const Icon(MoonIconsSports.set_tennis),
  const Icon(MoonIconsSports.skateboarding),
  const Icon(MoonIconsSports.ski_jumping),
  const Icon(MoonIconsSports.snooker),
  const Icon(MoonIconsSports.soccer),
  const Icon(MoonIconsSports.special_sports),
  const Icon(MoonIconsSports.specials),
  const Icon(MoonIconsSports.speedway),
  const Icon(MoonIconsSports.sportsbet),
  const Icon(MoonIconsSports.squash),
  const Icon(MoonIconsSports.surfing),
  const Icon(MoonIconsSports.swimming),
  const Icon(MoonIconsSports.table_tennis),
  const Icon(MoonIconsSports.tennis),
  const Icon(MoonIconsSports.triathlon),
  const Icon(MoonIconsSports.volleyball),
  const Icon(MoonIconsSports.waterpolo),
  const Icon(MoonIconsSports.weightlifting),
  const Icon(MoonIconsSports.wrestling),
];

final List<String> iconsSportsNameList = [
  "afl",
  "american_football",
  "archery",
  "athletics",
  "audl",
  "badminton",
  "baseball",
  "basketball",
  "beach_volleyball",
  "biathlon",
  "bombay",
  "bowls",
  "boxing",
  "call_of_duty",
  "canoeing",
  "car_racing",
  "casino",
  "chess",
  "cricket",
  "cross_country",
  "csgo",
  "curling",
  "cycling",
  "darts",
  "diving",
  "dota_2",
  "e_ice_hockey",
  "e_nba",
  "e_soccer",
  "equestrian",
  "esport_generic",
  "featured",
  "fencing",
  "field_hockey",
  "floorball",
  "formula_1",
  "formula_e",
  "futsal",
  "gaelic_hurling",
  "golf",
  "greyhound",
  "gymnastics",
  "handball",
  "harness",
  "horse_racing",
  "ice_hockey",
  "indy_racing",
  "judo",
  "kabaddi",
  "king_of_glory",
  "lacrosse",
  "lol",
  "mma",
  "motor",
  "motorcycle_racing",
  "nordic_combined",
  "olympics",
  "overwatch",
  "rainbow_six",
  "rocket_league",
  "rowing",
  "rugby",
  "sailing",
  "set_tennis",
  "skateboarding",
  "ski_jumping",
  "snooker",
  "soccer",
  "special_sports",
  "specials",
  "speedway",
  "sportsbet",
  "squash",
  "surfing",
  "swimming",
  "table_tennis",
  "tennis",
  "triathlon",
  "volleyball",
  "waterpolo",
  "weightlifting",
  "wrestling",
];
