import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsControlsList = [
  const Icon(MoonIconsControls.chevron_down_small16),
  const Icon(MoonIconsControls.chevron_down_small24),
  const Icon(MoonIconsControls.chevron_down_small32),
  const Icon(MoonIconsControls.chevron_down16),
  const Icon(MoonIconsControls.chevron_down24),
  const Icon(MoonIconsControls.chevron_down32),
  const Icon(MoonIconsControls.chevron_left_small16),
  const Icon(MoonIconsControls.chevron_left_small24),
  const Icon(MoonIconsControls.chevron_left_small32),
  const Icon(MoonIconsControls.chevron_left16),
  const Icon(MoonIconsControls.chevron_left24),
  const Icon(MoonIconsControls.chevron_left32),
  const Icon(MoonIconsControls.chevron_right_small16),
  const Icon(MoonIconsControls.chevron_right_small24),
  const Icon(MoonIconsControls.chevron_right_small32),
  const Icon(MoonIconsControls.chevron_right16),
  const Icon(MoonIconsControls.chevron_right24),
  const Icon(MoonIconsControls.chevron_right32),
  const Icon(MoonIconsControls.chevron_up_small16),
  const Icon(MoonIconsControls.chevron_up_small24),
  const Icon(MoonIconsControls.chevron_up_small32),
  const Icon(MoonIconsControls.chevron_up16),
  const Icon(MoonIconsControls.chevron_up24),
  const Icon(MoonIconsControls.chevron_up32),
  const Icon(MoonIconsControls.clear16),
  const Icon(MoonIconsControls.clear24),
  const Icon(MoonIconsControls.clear32),
  const Icon(MoonIconsControls.close_small16),
  const Icon(MoonIconsControls.close_small24),
  const Icon(MoonIconsControls.close_small32),
  const Icon(MoonIconsControls.close16),
  const Icon(MoonIconsControls.close24),
  const Icon(MoonIconsControls.close32),
  const Icon(MoonIconsControls.collapse16),
  const Icon(MoonIconsControls.collapse24),
  const Icon(MoonIconsControls.collapse32),
  const Icon(MoonIconsControls.diagonals_insight16),
  const Icon(MoonIconsControls.diagonals_insight24),
  const Icon(MoonIconsControls.diagonals_insight32),
  const Icon(MoonIconsControls.diagonals_outsight16),
  const Icon(MoonIconsControls.diagonals_outsight24),
  const Icon(MoonIconsControls.diagonals_outsight32),
  const Icon(MoonIconsControls.expand_alt16),
  const Icon(MoonIconsControls.expand_alt24),
  const Icon(MoonIconsControls.expand_alt32),
  const Icon(MoonIconsControls.expand16),
  const Icon(MoonIconsControls.expand24),
  const Icon(MoonIconsControls.expand32),
  const Icon(MoonIconsControls.eye_crossed16),
  const Icon(MoonIconsControls.eye_crossed24),
  const Icon(MoonIconsControls.eye_crossed32),
  const Icon(MoonIconsControls.eye16),
  const Icon(MoonIconsControls.eye24),
  const Icon(MoonIconsControls.eye32),
  const Icon(MoonIconsControls.full_screen_out16),
  const Icon(MoonIconsControls.full_screen_out24),
  const Icon(MoonIconsControls.full_screen_out32),
  const Icon(MoonIconsControls.full_screen16),
  const Icon(MoonIconsControls.full_screen24),
  const Icon(MoonIconsControls.full_screen32),
  const Icon(MoonIconsControls.minus16),
  const Icon(MoonIconsControls.minus24),
  const Icon(MoonIconsControls.minus32),
  const Icon(MoonIconsControls.plus16),
  const Icon(MoonIconsControls.plus24),
  const Icon(MoonIconsControls.plus32),
  const Icon(MoonIconsControls.vertical_double_chevron16),
  const Icon(MoonIconsControls.vertical_double_chevron24),
  const Icon(MoonIconsControls.vertical_double_chevron32),
];

final List<String> iconsControlsNameList = [
  "chevron_down_small16",
  "chevron_down_small24",
  "chevron_down_small32",
  "chevron_down16",
  "chevron_down24",
  "chevron_down32",
  "chevron_left_small16",
  "chevron_left_small24",
  "chevron_left_small32",
  "chevron_left16",
  "chevron_left24",
  "chevron_left32",
  "chevron_right_small16",
  "chevron_right_small24",
  "chevron_right_small32",
  "chevron_right16",
  "chevron_right24",
  "chevron_right32",
  "chevron_up_small16",
  "chevron_up_small24",
  "chevron_up_small32",
  "chevron_up16",
  "chevron_up24",
  "chevron_up32",
  "clear16",
  "clear24",
  "clear32",
  "close_small16",
  "close_small24",
  "close_small32",
  "close16",
  "close24",
  "close32",
  "collapse16",
  "collapse24",
  "collapse32",
  "diagonals_insight16",
  "diagonals_insight24",
  "diagonals_insight32",
  "diagonals_outsight16",
  "diagonals_outsight24",
  "diagonals_outsight32",
  "expand_alt16",
  "expand_alt24",
  "expand_alt32",
  "expand16",
  "expand24",
  "expand32",
  "eye_crossed16",
  "eye_crossed24",
  "eye_crossed32",
  "eye16",
  "eye24",
  "eye32",
  "full_screen_out16",
  "full_screen_out24",
  "full_screen_out32",
  "full_screen16",
  "full_screen24",
  "full_screen32",
  "minus16",
  "minus24",
  "minus32",
  "plus16",
  "plus24",
  "plus32",
  "vertical_double_chevron16",
  "vertical_double_chevron24",
  "vertical_double_chevron32",
];
