import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsNotificationsList = [
  const Icon(MoonIconsNotifications.activity16),
  const Icon(MoonIconsNotifications.activity24),
  const Icon(MoonIconsNotifications.activity32),
  const Icon(MoonIconsNotifications.add_bell16),
  const Icon(MoonIconsNotifications.add_bell24),
  const Icon(MoonIconsNotifications.add_bell32),
  const Icon(MoonIconsNotifications.alert16),
  const Icon(MoonIconsNotifications.alert24),
  const Icon(MoonIconsNotifications.alert32),
  const Icon(MoonIconsNotifications.app16),
  const Icon(MoonIconsNotifications.app24),
  const Icon(MoonIconsNotifications.app32),
  const Icon(MoonIconsNotifications.bell_alarm16),
  const Icon(MoonIconsNotifications.bell_alarm24),
  const Icon(MoonIconsNotifications.bell_alarm32),
  const Icon(MoonIconsNotifications.bell_cross16),
  const Icon(MoonIconsNotifications.bell_cross24),
  const Icon(MoonIconsNotifications.bell_cross32),
  const Icon(MoonIconsNotifications.bell_ringing_alternative16),
  const Icon(MoonIconsNotifications.bell_ringing_alternative24),
  const Icon(MoonIconsNotifications.bell_ringing_alternative32),
  const Icon(MoonIconsNotifications.bell_ringing16),
  const Icon(MoonIconsNotifications.bell_ringing24),
  const Icon(MoonIconsNotifications.bell_ringing32),
  const Icon(MoonIconsNotifications.bell16),
  const Icon(MoonIconsNotifications.bell24),
  const Icon(MoonIconsNotifications.bell32),
  const Icon(MoonIconsNotifications.error16),
  const Icon(MoonIconsNotifications.error24),
  const Icon(MoonIconsNotifications.error32),
  const Icon(MoonIconsNotifications.notifications16),
  const Icon(MoonIconsNotifications.notifications24),
  const Icon(MoonIconsNotifications.notifications32),
  const Icon(MoonIconsNotifications.question_mark16),
  const Icon(MoonIconsNotifications.question_mark24),
  const Icon(MoonIconsNotifications.question_mark32),
  const Icon(MoonIconsNotifications.settings16),
  const Icon(MoonIconsNotifications.settings24),
  const Icon(MoonIconsNotifications.settings32),
];

final List<String> iconsNotificationsNameList = [
  "activity16",
  "activity24",
  "activity32",
  "add_bell16",
  "add_bell24",
  "add_bell32",
  "alert16",
  "alert24",
  "alert32",
  "app16",
  "app24",
  "app32",
  "bell_alarm16",
  "bell_alarm24",
  "bell_alarm32",
  "bell_cross16",
  "bell_cross24",
  "bell_cross32",
  "bell_ringing_alternative16",
  "bell_ringing_alternative24",
  "bell_ringing_alternative32",
  "bell_ringing16",
  "bell_ringing24",
  "bell_ringing32",
  "bell16",
  "bell24",
  "bell32",
  "error16",
  "error24",
  "error32",
  "notifications16",
  "notifications24",
  "notifications32",
  "question_mark16",
  "question_mark24",
  "question_mark32",
  "settings16",
  "settings24",
  "settings32",
];
