import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsTimeList = [
  const Icon(MoonIconsTime.alarm16),
  const Icon(MoonIconsTime.alarm24),
  const Icon(MoonIconsTime.alarm32),
  const Icon(MoonIconsTime.calendar_add16),
  const Icon(MoonIconsTime.calendar_add24),
  const Icon(MoonIconsTime.calendar_add32),
  const Icon(MoonIconsTime.calendar_alternative16),
  const Icon(MoonIconsTime.calendar_alternative24),
  const Icon(MoonIconsTime.calendar_alternative32),
  const Icon(MoonIconsTime.calendar_date16),
  const Icon(MoonIconsTime.calendar_date24),
  const Icon(MoonIconsTime.calendar_date32),
  const Icon(MoonIconsTime.calendar_remove16),
  const Icon(MoonIconsTime.calendar_remove24),
  const Icon(MoonIconsTime.calendar_remove32),
  const Icon(MoonIconsTime.calendar_success16),
  const Icon(MoonIconsTime.calendar_success24),
  const Icon(MoonIconsTime.calendar_success32),
  const Icon(MoonIconsTime.calendar16),
  const Icon(MoonIconsTime.calendar24),
  const Icon(MoonIconsTime.calendar32),
  const Icon(MoonIconsTime.clock16),
  const Icon(MoonIconsTime.clock24),
  const Icon(MoonIconsTime.clock32),
  const Icon(MoonIconsTime.sandglass16),
  const Icon(MoonIconsTime.sandglass24),
  const Icon(MoonIconsTime.sandglass32),
  const Icon(MoonIconsTime.stopwatch_timer16),
  const Icon(MoonIconsTime.stopwatch_timer24),
  const Icon(MoonIconsTime.stopwatch_timer32),
  const Icon(MoonIconsTime.stopwatch16),
  const Icon(MoonIconsTime.stopwatch24),
  const Icon(MoonIconsTime.stopwatch32),
  const Icon(MoonIconsTime.time16),
  const Icon(MoonIconsTime.time24),
  const Icon(MoonIconsTime.time32),
  const Icon(MoonIconsTime.watch16),
  const Icon(MoonIconsTime.watch24),
  const Icon(MoonIconsTime.watch32),
];

final List<String> iconsTimeNameList = [
  "alarm16",
  "alarm24",
  "alarm32",
  "calendar_add16",
  "calendar_add24",
  "calendar_add32",
  "calendar_alternative16",
  "calendar_alternative24",
  "calendar_alternative32",
  "calendar_date16",
  "calendar_date24",
  "calendar_date32",
  "calendar_remove16",
  "calendar_remove24",
  "calendar_remove32",
  "calendar_success16",
  "calendar_success24",
  "calendar_success32",
  "calendar16",
  "calendar24",
  "calendar32",
  "clock16",
  "clock24",
  "clock32",
  "sandglass16",
  "sandglass24",
  "sandglass32",
  "stopwatch_timer16",
  "stopwatch_timer24",
  "stopwatch_timer32",
  "stopwatch16",
  "stopwatch24",
  "stopwatch32",
  "time16",
  "time24",
  "time32",
  "watch16",
  "watch24",
  "watch32",
];
