import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsTextEditList = [
  const Icon(MoonIconsTextEdit.anchor16),
  const Icon(MoonIconsTextEdit.anchor24),
  const Icon(MoonIconsTextEdit.anchor32),
  const Icon(MoonIconsTextEdit.attach16),
  const Icon(MoonIconsTextEdit.attach24),
  const Icon(MoonIconsTextEdit.attach32),
  const Icon(MoonIconsTextEdit.bold16),
  const Icon(MoonIconsTextEdit.bold24),
  const Icon(MoonIconsTextEdit.bold32),
  const Icon(MoonIconsTextEdit.bullets_list16),
  const Icon(MoonIconsTextEdit.bullets_list24),
  const Icon(MoonIconsTextEdit.bullets_list32),
  const Icon(MoonIconsTextEdit.cards16),
  const Icon(MoonIconsTextEdit.cards24),
  const Icon(MoonIconsTextEdit.cards32),
  const Icon(MoonIconsTextEdit.center16),
  const Icon(MoonIconsTextEdit.center24),
  const Icon(MoonIconsTextEdit.center32),
  const Icon(MoonIconsTextEdit.clear_formatting16),
  const Icon(MoonIconsTextEdit.clear_formatting24),
  const Icon(MoonIconsTextEdit.clear_formatting32),
  const Icon(MoonIconsTextEdit.cut16),
  const Icon(MoonIconsTextEdit.cut24),
  const Icon(MoonIconsTextEdit.cut32),
  const Icon(MoonIconsTextEdit.decrease_indent16),
  const Icon(MoonIconsTextEdit.decrease_indent24),
  const Icon(MoonIconsTextEdit.decrease_indent32),
  const Icon(MoonIconsTextEdit.hashtag16),
  const Icon(MoonIconsTextEdit.hashtag24),
  const Icon(MoonIconsTextEdit.hashtag32),
  const Icon(MoonIconsTextEdit.increase_indent16),
  const Icon(MoonIconsTextEdit.increase_indent24),
  const Icon(MoonIconsTextEdit.increase_indent32),
  const Icon(MoonIconsTextEdit.insert_line16),
  const Icon(MoonIconsTextEdit.insert_line24),
  const Icon(MoonIconsTextEdit.insert_line32),
  const Icon(MoonIconsTextEdit.italic16),
  const Icon(MoonIconsTextEdit.italic24),
  const Icon(MoonIconsTextEdit.italic32),
  const Icon(MoonIconsTextEdit.left_align16),
  const Icon(MoonIconsTextEdit.left_align24),
  const Icon(MoonIconsTextEdit.left_align32),
  const Icon(MoonIconsTextEdit.list_view16),
  const Icon(MoonIconsTextEdit.list_view24),
  const Icon(MoonIconsTextEdit.list_view32),
  const Icon(MoonIconsTextEdit.marker16),
  const Icon(MoonIconsTextEdit.marker24),
  const Icon(MoonIconsTextEdit.marker32),
  const Icon(MoonIconsTextEdit.math16),
  const Icon(MoonIconsTextEdit.math24),
  const Icon(MoonIconsTextEdit.math32),
  const Icon(MoonIconsTextEdit.numbers_list16),
  const Icon(MoonIconsTextEdit.numbers_list24),
  const Icon(MoonIconsTextEdit.numbers_list32),
  const Icon(MoonIconsTextEdit.right_align16),
  const Icon(MoonIconsTextEdit.right_align24),
  const Icon(MoonIconsTextEdit.right_align32),
  const Icon(MoonIconsTextEdit.size16),
  const Icon(MoonIconsTextEdit.size24),
  const Icon(MoonIconsTextEdit.size32),
  const Icon(MoonIconsTextEdit.strikethrough16),
  const Icon(MoonIconsTextEdit.strikethrough24),
  const Icon(MoonIconsTextEdit.strikethrough32),
  const Icon(MoonIconsTextEdit.style16),
  const Icon(MoonIconsTextEdit.style24),
  const Icon(MoonIconsTextEdit.style32),
  const Icon(MoonIconsTextEdit.table_alternative16),
  const Icon(MoonIconsTextEdit.table_alternative24),
  const Icon(MoonIconsTextEdit.table_alternative32),
  const Icon(MoonIconsTextEdit.table16),
  const Icon(MoonIconsTextEdit.table24),
  const Icon(MoonIconsTextEdit.table32),
  const Icon(MoonIconsTextEdit.underline16),
  const Icon(MoonIconsTextEdit.underline24),
  const Icon(MoonIconsTextEdit.underline32),
];

final List<String> iconsTextEditNameList = [
  "anchor16",
  "anchor24",
  "anchor32",
  "attach16",
  "attach24",
  "attach32",
  "bold16",
  "bold24",
  "bold32",
  "bullets_list16",
  "bullets_list24",
  "bullets_list32",
  "cards16",
  "cards24",
  "cards32",
  "center16",
  "center24",
  "center32",
  "clear_formatting16",
  "clear_formatting24",
  "clear_formatting32",
  "cut16",
  "cut24",
  "cut32",
  "decrease_indent16",
  "decrease_indent24",
  "decrease_indent32",
  "hashtag16",
  "hashtag24",
  "hashtag32",
  "increase_indent16",
  "increase_indent24",
  "increase_indent32",
  "insert_line16",
  "insert_line24",
  "insert_line32",
  "italic16",
  "italic24",
  "italic32",
  "left_align16",
  "left_align24",
  "left_align32",
  "list_view16",
  "list_view24",
  "list_view32",
  "marker16",
  "marker24",
  "marker32",
  "math16",
  "math24",
  "math32",
  "numbers_list16",
  "numbers_list24",
  "numbers_list32",
  "right_align16",
  "right_align24",
  "right_align32",
  "size16",
  "size24",
  "size32",
  "strikethrough16",
  "strikethrough24",
  "strikethrough32",
  "style16",
  "style24",
  "style32",
  "table_alternative16",
  "table_alternative24",
  "table_alternative32",
  "table16",
  "table24",
  "table32",
  "underline16",
  "underline24",
  "underline32",
];
