import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsList = [
  const Icon(MoonIcons.about_16),
  const Icon(MoonIcons.about_24),
  const Icon(MoonIcons.about_32),
  const Icon(MoonIcons.activity_16),
  const Icon(MoonIcons.activity_24),
  const Icon(MoonIcons.activity_32),
  const Icon(MoonIcons.add_16),
  const Icon(MoonIcons.add_24),
  const Icon(MoonIcons.add_32),
  const Icon(MoonIcons.add_bell_16),
  const Icon(MoonIcons.add_bell_24),
  const Icon(MoonIcons.add_bell_32),
  const Icon(MoonIcons.add_text_16),
  const Icon(MoonIcons.add_text_24),
  const Icon(MoonIcons.add_text_32),
  const Icon(MoonIcons.airplane_16),
  const Icon(MoonIcons.airplane_24),
  const Icon(MoonIcons.airplane_32),
  const Icon(MoonIcons.airplane_down_16),
  const Icon(MoonIcons.airplane_down_24),
  const Icon(MoonIcons.airplane_down_32),
  const Icon(MoonIcons.airplane_up_16),
  const Icon(MoonIcons.airplane_up_24),
  const Icon(MoonIcons.airplane_up_32),
  const Icon(MoonIcons.alarm_round_16),
  const Icon(MoonIcons.alarm_round_24),
  const Icon(MoonIcons.alarm_round_32),
  const Icon(MoonIcons.alert_16),
  const Icon(MoonIcons.alert_24),
  const Icon(MoonIcons.alert_32),
  const Icon(MoonIcons.all_16),
  const Icon(MoonIcons.all_24),
  const Icon(MoonIcons.all_32),
  const Icon(MoonIcons.anchor_16),
  const Icon(MoonIcons.anchor_24),
  const Icon(MoonIcons.anchor_32),
  const Icon(MoonIcons.app_16),
  const Icon(MoonIcons.app_24),
  const Icon(MoonIcons.app_32),
  const Icon(MoonIcons.area_16),
  const Icon(MoonIcons.area_24),
  const Icon(MoonIcons.area_32),
  const Icon(MoonIcons.attach_16),
  const Icon(MoonIcons.attach_24),
  const Icon(MoonIcons.attach_32),
  const Icon(MoonIcons.auto_play_16),
  const Icon(MoonIcons.auto_play_24),
  const Icon(MoonIcons.auto_play_32),
  const Icon(MoonIcons.bag_16),
  const Icon(MoonIcons.bag_24),
  const Icon(MoonIcons.bag_32),
  const Icon(MoonIcons.bank_16),
  const Icon(MoonIcons.bank_24),
  const Icon(MoonIcons.bank_32),
  const Icon(MoonIcons.bar_16),
  const Icon(MoonIcons.bar_24),
  const Icon(MoonIcons.bar_32),
  const Icon(MoonIcons.bar_alternative_16),
  const Icon(MoonIcons.bar_alternative_24),
  const Icon(MoonIcons.bar_alternative_32),
  const Icon(MoonIcons.bar_vertical_16),
  const Icon(MoonIcons.bar_vertical_24),
  const Icon(MoonIcons.bar_vertical_32),
  const Icon(MoonIcons.basket_16),
  const Icon(MoonIcons.basket_24),
  const Icon(MoonIcons.basket_32),
  const Icon(MoonIcons.beach_chair_16),
  const Icon(MoonIcons.beach_chair_24),
  const Icon(MoonIcons.beach_chair_32),
  const Icon(MoonIcons.bed_16),
  const Icon(MoonIcons.bed_24),
  const Icon(MoonIcons.bed_32),
  const Icon(MoonIcons.bell_16),
  const Icon(MoonIcons.bell_24),
  const Icon(MoonIcons.bell_32),
  const Icon(MoonIcons.bell_alarm_16),
  const Icon(MoonIcons.bell_alarm_24),
  const Icon(MoonIcons.bell_alarm_32),
  const Icon(MoonIcons.bell_cross_16),
  const Icon(MoonIcons.bell_cross_24),
  const Icon(MoonIcons.bell_cross_32),
  const Icon(MoonIcons.bell_ringing_16),
  const Icon(MoonIcons.bell_ringing_24),
  const Icon(MoonIcons.bell_ringing_32),
  const Icon(MoonIcons.bell_ringing_alternative_16),
  const Icon(MoonIcons.bell_ringing_alternative_24),
  const Icon(MoonIcons.bell_ringing_alternative_32),
  const Icon(MoonIcons.bet_16),
  const Icon(MoonIcons.bet_24),
  const Icon(MoonIcons.bet_32),
  const Icon(MoonIcons.bet_insurance_16),
  const Icon(MoonIcons.bet_insurance_24),
  const Icon(MoonIcons.bet_insurance_32),
  const Icon(MoonIcons.betslip_16),
  const Icon(MoonIcons.betslip_24),
  const Icon(MoonIcons.betslip_32),
  const Icon(MoonIcons.bill_16),
  const Icon(MoonIcons.bill_24),
  const Icon(MoonIcons.bill_32),
  const Icon(MoonIcons.block_16),
  const Icon(MoonIcons.block_24),
  const Icon(MoonIcons.block_32),
  const Icon(MoonIcons.bluetooth_16),
  const Icon(MoonIcons.bluetooth_24),
  const Icon(MoonIcons.bluetooth_32),
  const Icon(MoonIcons.bold_16),
  const Icon(MoonIcons.bold_24),
  const Icon(MoonIcons.bold_32),
  const Icon(MoonIcons.bookmark_16),
  const Icon(MoonIcons.bookmark_24),
  const Icon(MoonIcons.bookmark_32),
  const Icon(MoonIcons.bookmark_alternative_16),
  const Icon(MoonIcons.bookmark_alternative_24),
  const Icon(MoonIcons.bookmark_alternative_32),
  const Icon(MoonIcons.boost_16),
  const Icon(MoonIcons.boost_24),
  const Icon(MoonIcons.boost_32),
  const Icon(MoonIcons.bottom_left_16),
  const Icon(MoonIcons.bottom_left_24),
  const Icon(MoonIcons.bottom_left_32),
  const Icon(MoonIcons.bottom_right_16),
  const Icon(MoonIcons.bottom_right_24),
  const Icon(MoonIcons.bottom_right_32),
  const Icon(MoonIcons.box_16),
  const Icon(MoonIcons.box_24),
  const Icon(MoonIcons.box_32),
  const Icon(MoonIcons.browser_16),
  const Icon(MoonIcons.browser_24),
  const Icon(MoonIcons.browser_32),
  const Icon(MoonIcons.bug_16),
  const Icon(MoonIcons.bug_24),
  const Icon(MoonIcons.bug_32),
  const Icon(MoonIcons.bullets_list_16),
  const Icon(MoonIcons.bullets_list_24),
  const Icon(MoonIcons.bullets_list_32),
  const Icon(MoonIcons.burger_regular_16),
  const Icon(MoonIcons.burger_regular_24),
  const Icon(MoonIcons.burger_regular_32),
  const Icon(MoonIcons.burger_zig_16),
  const Icon(MoonIcons.burger_zig_24),
  const Icon(MoonIcons.burger_zig_32),
  const Icon(MoonIcons.buy_crypto_16),
  const Icon(MoonIcons.buy_crypto_24),
  const Icon(MoonIcons.buy_crypto_32),
  const Icon(MoonIcons.calendar_16),
  const Icon(MoonIcons.calendar_24),
  const Icon(MoonIcons.calendar_32),
  const Icon(MoonIcons.calendar_add_16),
  const Icon(MoonIcons.calendar_add_24),
  const Icon(MoonIcons.calendar_add_32),
  const Icon(MoonIcons.calendar_alternative_16),
  const Icon(MoonIcons.calendar_alternative_24),
  const Icon(MoonIcons.calendar_alternative_32),
  const Icon(MoonIcons.calendar_date_16),
  const Icon(MoonIcons.calendar_date_24),
  const Icon(MoonIcons.calendar_date_32),
  const Icon(MoonIcons.calendar_remove_16),
  const Icon(MoonIcons.calendar_remove_24),
  const Icon(MoonIcons.calendar_remove_32),
  const Icon(MoonIcons.calendar_success_16),
  const Icon(MoonIcons.calendar_success_24),
  const Icon(MoonIcons.calendar_success_32),
  const Icon(MoonIcons.card_16),
  const Icon(MoonIcons.card_24),
  const Icon(MoonIcons.card_32),
  const Icon(MoonIcons.cards_16),
  const Icon(MoonIcons.cards_24),
  const Icon(MoonIcons.cards_32),
  const Icon(MoonIcons.cart_16),
  const Icon(MoonIcons.cart_24),
  const Icon(MoonIcons.cart_32),
  const Icon(MoonIcons.case_16),
  const Icon(MoonIcons.case_24),
  const Icon(MoonIcons.case_32),
  const Icon(MoonIcons.center_16),
  const Icon(MoonIcons.center_24),
  const Icon(MoonIcons.center_32),
  const Icon(MoonIcons.chat_16),
  const Icon(MoonIcons.chat_24),
  const Icon(MoonIcons.chat_32),
  const Icon(MoonIcons.check_alternative_16),
  const Icon(MoonIcons.check_alternative_24),
  const Icon(MoonIcons.check_alternative_32),
  const Icon(MoonIcons.check_rounded_16),
  const Icon(MoonIcons.check_rounded_24),
  const Icon(MoonIcons.check_rounded_32),
  const Icon(MoonIcons.chevron_down_16),
  const Icon(MoonIcons.chevron_down_24),
  const Icon(MoonIcons.chevron_down_32),
  const Icon(MoonIcons.chevron_down_double_16),
  const Icon(MoonIcons.chevron_down_double_24),
  const Icon(MoonIcons.chevron_down_double_32),
  const Icon(MoonIcons.chevron_down_small_16),
  const Icon(MoonIcons.chevron_down_small_24),
  const Icon(MoonIcons.chevron_down_small_32),
  const Icon(MoonIcons.chevron_left_16),
  const Icon(MoonIcons.chevron_left_24),
  const Icon(MoonIcons.chevron_left_32),
  const Icon(MoonIcons.chevron_left_double_16),
  const Icon(MoonIcons.chevron_left_double_24),
  const Icon(MoonIcons.chevron_left_double_32),
  const Icon(MoonIcons.chevron_left_small_16),
  const Icon(MoonIcons.chevron_left_small_24),
  const Icon(MoonIcons.chevron_left_small_32),
  const Icon(MoonIcons.chevron_right_16),
  const Icon(MoonIcons.chevron_right_24),
  const Icon(MoonIcons.chevron_right_32),
  const Icon(MoonIcons.chevron_right_double_16),
  const Icon(MoonIcons.chevron_right_double_24),
  const Icon(MoonIcons.chevron_right_double_32),
  const Icon(MoonIcons.chevron_right_small_16),
  const Icon(MoonIcons.chevron_right_small_24),
  const Icon(MoonIcons.chevron_right_small_32),
  const Icon(MoonIcons.chevron_up_16),
  const Icon(MoonIcons.chevron_up_24),
  const Icon(MoonIcons.chevron_up_32),
  const Icon(MoonIcons.chevron_up_double_16),
  const Icon(MoonIcons.chevron_up_double_24),
  const Icon(MoonIcons.chevron_up_double_32),
  const Icon(MoonIcons.chevron_up_small_16),
  const Icon(MoonIcons.chevron_up_small_24),
  const Icon(MoonIcons.chevron_up_small_32),
  const Icon(MoonIcons.claps_16),
  const Icon(MoonIcons.claps_24),
  const Icon(MoonIcons.claps_32),
  const Icon(MoonIcons.clear_16),
  const Icon(MoonIcons.clear_24),
  const Icon(MoonIcons.clear_32),
  const Icon(MoonIcons.clear_formatting_16),
  const Icon(MoonIcons.clear_formatting_24),
  const Icon(MoonIcons.clear_formatting_32),
  const Icon(MoonIcons.clipboard_16),
  const Icon(MoonIcons.clipboard_24),
  const Icon(MoonIcons.clipboard_32),
  const Icon(MoonIcons.clipboard_text_16),
  const Icon(MoonIcons.clipboard_text_24),
  const Icon(MoonIcons.clipboard_text_32),
  const Icon(MoonIcons.clock_16),
  const Icon(MoonIcons.clock_24),
  const Icon(MoonIcons.clock_32),
  const Icon(MoonIcons.clock_alarm_16),
  const Icon(MoonIcons.clock_alarm_24),
  const Icon(MoonIcons.clock_alarm_32),
  const Icon(MoonIcons.close_16),
  const Icon(MoonIcons.close_24),
  const Icon(MoonIcons.close_32),
  const Icon(MoonIcons.close_circular_16),
  const Icon(MoonIcons.close_circular_24),
  const Icon(MoonIcons.close_circular_32),
  const Icon(MoonIcons.close_small_16),
  const Icon(MoonIcons.close_small_24),
  const Icon(MoonIcons.close_small_32),
  const Icon(MoonIcons.cloud_download_16),
  const Icon(MoonIcons.cloud_download_24),
  const Icon(MoonIcons.cloud_download_32),
  const Icon(MoonIcons.code_16),
  const Icon(MoonIcons.code_24),
  const Icon(MoonIcons.code_32),
  const Icon(MoonIcons.code_file_16),
  const Icon(MoonIcons.code_file_24),
  const Icon(MoonIcons.code_file_32),
  const Icon(MoonIcons.coins_16),
  const Icon(MoonIcons.coins_24),
  const Icon(MoonIcons.coins_32),
  const Icon(MoonIcons.collapse_16),
  const Icon(MoonIcons.collapse_24),
  const Icon(MoonIcons.collapse_32),
  const Icon(MoonIcons.comment_16),
  const Icon(MoonIcons.comment_24),
  const Icon(MoonIcons.comment_32),
  const Icon(MoonIcons.comment_add_16),
  const Icon(MoonIcons.comment_add_24),
  const Icon(MoonIcons.comment_add_32),
  const Icon(MoonIcons.comment_bubble_16),
  const Icon(MoonIcons.comment_bubble_24),
  const Icon(MoonIcons.comment_bubble_32),
  const Icon(MoonIcons.comment_bubble_alert_16),
  const Icon(MoonIcons.comment_bubble_alert_24),
  const Icon(MoonIcons.comment_bubble_alert_32),
  const Icon(MoonIcons.comment_bubble_question_mark_16),
  const Icon(MoonIcons.comment_bubble_question_mark_24),
  const Icon(MoonIcons.comment_bubble_question_mark_32),
  const Icon(MoonIcons.comment_remove_16),
  const Icon(MoonIcons.comment_remove_24),
  const Icon(MoonIcons.comment_remove_32),
  const Icon(MoonIcons.comment_text_16),
  const Icon(MoonIcons.comment_text_24),
  const Icon(MoonIcons.comment_text_32),
  const Icon(MoonIcons.compass_16),
  const Icon(MoonIcons.compass_24),
  const Icon(MoonIcons.compass_32),
  const Icon(MoonIcons.copy_16),
  const Icon(MoonIcons.copy_24),
  const Icon(MoonIcons.copy_32),
  const Icon(MoonIcons.cross_lines_16),
  const Icon(MoonIcons.cross_lines_24),
  const Icon(MoonIcons.cross_lines_32),
  const Icon(MoonIcons.crown_16),
  const Icon(MoonIcons.crown_24),
  const Icon(MoonIcons.crown_32),
  const Icon(MoonIcons.crypto_16),
  const Icon(MoonIcons.crypto_24),
  const Icon(MoonIcons.crypto_32),
  const Icon(MoonIcons.crypto_coin_16),
  const Icon(MoonIcons.crypto_coin_24),
  const Icon(MoonIcons.crypto_coin_32),
  const Icon(MoonIcons.css_16),
  const Icon(MoonIcons.css_24),
  const Icon(MoonIcons.css_32),
  const Icon(MoonIcons.csv_16),
  const Icon(MoonIcons.csv_24),
  const Icon(MoonIcons.csv_32),
  const Icon(MoonIcons.cursor_16),
  const Icon(MoonIcons.cursor_24),
  const Icon(MoonIcons.cursor_32),
  const Icon(MoonIcons.cut_16),
  const Icon(MoonIcons.cut_24),
  const Icon(MoonIcons.cut_32),
  const Icon(MoonIcons.data_16),
  const Icon(MoonIcons.data_24),
  const Icon(MoonIcons.data_32),
  const Icon(MoonIcons.decrease_indent_16),
  const Icon(MoonIcons.decrease_indent_24),
  const Icon(MoonIcons.decrease_indent_32),
  const Icon(MoonIcons.delete_16),
  const Icon(MoonIcons.delete_24),
  const Icon(MoonIcons.delete_32),
  const Icon(MoonIcons.desk_bell_16),
  const Icon(MoonIcons.desk_bell_24),
  const Icon(MoonIcons.desk_bell_32),
  const Icon(MoonIcons.diagonals_bltr_16),
  const Icon(MoonIcons.diagonals_bltr_24),
  const Icon(MoonIcons.diagonals_bltr_32),
  const Icon(MoonIcons.diagonals_insight_16),
  const Icon(MoonIcons.diagonals_insight_24),
  const Icon(MoonIcons.diagonals_insight_32),
  const Icon(MoonIcons.diagonals_outsight_16),
  const Icon(MoonIcons.diagonals_outsight_24),
  const Icon(MoonIcons.diagonals_outsight_32),
  const Icon(MoonIcons.diagonals_tlbr_16),
  const Icon(MoonIcons.diagonals_tlbr_24),
  const Icon(MoonIcons.diagonals_tlbr_32),
  const Icon(MoonIcons.dislike_16),
  const Icon(MoonIcons.dislike_24),
  const Icon(MoonIcons.dislike_32),
  const Icon(MoonIcons.double_bubble_16),
  const Icon(MoonIcons.double_bubble_24),
  const Icon(MoonIcons.double_bubble_32),
  const Icon(MoonIcons.down_16),
  const Icon(MoonIcons.down_24),
  const Icon(MoonIcons.down_32),
  const Icon(MoonIcons.download_16),
  const Icon(MoonIcons.download_24),
  const Icon(MoonIcons.download_32),
  const Icon(MoonIcons.draft_16),
  const Icon(MoonIcons.draft_24),
  const Icon(MoonIcons.draft_32),
  const Icon(MoonIcons.drag_handle_16),
  const Icon(MoonIcons.drag_handle_24),
  const Icon(MoonIcons.drag_handle_32),
  const Icon(MoonIcons.edit_16),
  const Icon(MoonIcons.edit_24),
  const Icon(MoonIcons.edit_32),
  const Icon(MoonIcons.email_stats_16),
  const Icon(MoonIcons.email_stats_24),
  const Icon(MoonIcons.email_stats_32),
  const Icon(MoonIcons.envelope_16),
  const Icon(MoonIcons.envelope_24),
  const Icon(MoonIcons.envelope_32),
  const Icon(MoonIcons.error_16),
  const Icon(MoonIcons.error_24),
  const Icon(MoonIcons.error_32),
  const Icon(MoonIcons.exe_16),
  const Icon(MoonIcons.exe_24),
  const Icon(MoonIcons.exe_32),
  const Icon(MoonIcons.expand_16),
  const Icon(MoonIcons.expand_24),
  const Icon(MoonIcons.expand_32),
  const Icon(MoonIcons.expand_alt_16),
  const Icon(MoonIcons.expand_alt_24),
  const Icon(MoonIcons.expand_alt_32),
  const Icon(MoonIcons.expand_rows_16),
  const Icon(MoonIcons.expand_rows_24),
  const Icon(MoonIcons.expand_rows_32),
  const Icon(MoonIcons.export_16),
  const Icon(MoonIcons.export_24),
  const Icon(MoonIcons.export_32),
  const Icon(MoonIcons.external_link_16),
  const Icon(MoonIcons.external_link_24),
  const Icon(MoonIcons.external_link_32),
  const Icon(MoonIcons.eye_16),
  const Icon(MoonIcons.eye_24),
  const Icon(MoonIcons.eye_32),
  const Icon(MoonIcons.eye_crossed_16),
  const Icon(MoonIcons.eye_crossed_24),
  const Icon(MoonIcons.eye_crossed_32),
  const Icon(MoonIcons.fast_back_16),
  const Icon(MoonIcons.fast_back_24),
  const Icon(MoonIcons.fast_back_32),
  const Icon(MoonIcons.fast_forward_16),
  const Icon(MoonIcons.fast_forward_24),
  const Icon(MoonIcons.fast_forward_32),
  const Icon(MoonIcons.file_16),
  const Icon(MoonIcons.file_24),
  const Icon(MoonIcons.file_32),
  const Icon(MoonIcons.file_table_16),
  const Icon(MoonIcons.file_table_24),
  const Icon(MoonIcons.file_table_32),
  const Icon(MoonIcons.filter_16),
  const Icon(MoonIcons.filter_24),
  const Icon(MoonIcons.filter_32),
  const Icon(MoonIcons.filter_crossed_16),
  const Icon(MoonIcons.filter_crossed_24),
  const Icon(MoonIcons.filter_crossed_32),
  const Icon(MoonIcons.fin_16),
  const Icon(MoonIcons.fin_24),
  const Icon(MoonIcons.fin_32),
  const Icon(MoonIcons.flag_16),
  const Icon(MoonIcons.flag_24),
  const Icon(MoonIcons.flag_32),
  const Icon(MoonIcons.flame_16),
  const Icon(MoonIcons.flame_24),
  const Icon(MoonIcons.flame_32),
  const Icon(MoonIcons.folder_closed_16),
  const Icon(MoonIcons.folder_closed_24),
  const Icon(MoonIcons.folder_closed_32),
  const Icon(MoonIcons.folder_open_16),
  const Icon(MoonIcons.folder_open_24),
  const Icon(MoonIcons.folder_open_32),
  const Icon(MoonIcons.folder_open_alternative_16),
  const Icon(MoonIcons.folder_open_alternative_24),
  const Icon(MoonIcons.folder_open_alternative_32),
  const Icon(MoonIcons.folder_zip_16),
  const Icon(MoonIcons.folder_zip_24),
  const Icon(MoonIcons.folder_zip_32),
  const Icon(MoonIcons.forward_16),
  const Icon(MoonIcons.forward_24),
  const Icon(MoonIcons.forward_32),
  const Icon(MoonIcons.four_three_free_16),
  const Icon(MoonIcons.four_three_free_24),
  const Icon(MoonIcons.four_three_free_32),
  const Icon(MoonIcons.frame_16),
  const Icon(MoonIcons.frame_24),
  const Icon(MoonIcons.frame_32),
  const Icon(MoonIcons.freebet_16),
  const Icon(MoonIcons.freebet_24),
  const Icon(MoonIcons.freebet_32),
  const Icon(MoonIcons.full_screen_16),
  const Icon(MoonIcons.full_screen_24),
  const Icon(MoonIcons.full_screen_32),
  const Icon(MoonIcons.full_screen_out_16),
  const Icon(MoonIcons.full_screen_out_24),
  const Icon(MoonIcons.full_screen_out_32),
  const Icon(MoonIcons.gif_alternative_16),
  const Icon(MoonIcons.gif_alternative_24),
  const Icon(MoonIcons.gif_alternative_32),
  const Icon(MoonIcons.glasses_16),
  const Icon(MoonIcons.glasses_24),
  const Icon(MoonIcons.glasses_32),
  const Icon(MoonIcons.globe_16),
  const Icon(MoonIcons.globe_24),
  const Icon(MoonIcons.globe_32),
  const Icon(MoonIcons.hand_16),
  const Icon(MoonIcons.hand_24),
  const Icon(MoonIcons.hand_32),
  const Icon(MoonIcons.hashtag_16),
  const Icon(MoonIcons.hashtag_24),
  const Icon(MoonIcons.hashtag_32),
  const Icon(MoonIcons.headphones_16),
  const Icon(MoonIcons.headphones_24),
  const Icon(MoonIcons.headphones_32),
  const Icon(MoonIcons.heart_16),
  const Icon(MoonIcons.heart_24),
  const Icon(MoonIcons.heart_32),
  const Icon(MoonIcons.help_16),
  const Icon(MoonIcons.help_24),
  const Icon(MoonIcons.help_32),
  const Icon(MoonIcons.home_16),
  const Icon(MoonIcons.home_24),
  const Icon(MoonIcons.home_32),
  const Icon(MoonIcons.hotel_16),
  const Icon(MoonIcons.hotel_24),
  const Icon(MoonIcons.hotel_32),
  const Icon(MoonIcons.html_16),
  const Icon(MoonIcons.html_24),
  const Icon(MoonIcons.html_32),
  const Icon(MoonIcons.hyperlink_16),
  const Icon(MoonIcons.hyperlink_24),
  const Icon(MoonIcons.hyperlink_32),
  const Icon(MoonIcons.id_16),
  const Icon(MoonIcons.id_24),
  const Icon(MoonIcons.id_32),
  const Icon(MoonIcons.idea_16),
  const Icon(MoonIcons.idea_24),
  const Icon(MoonIcons.idea_32),
  const Icon(MoonIcons.import_16),
  const Icon(MoonIcons.import_24),
  const Icon(MoonIcons.import_32),
  const Icon(MoonIcons.increase_indent_16),
  const Icon(MoonIcons.increase_indent_24),
  const Icon(MoonIcons.increase_indent_32),
  const Icon(MoonIcons.info_16),
  const Icon(MoonIcons.info_24),
  const Icon(MoonIcons.info_32),
  const Icon(MoonIcons.info_alternative_16),
  const Icon(MoonIcons.info_alternative_24),
  const Icon(MoonIcons.info_alternative_32),
  const Icon(MoonIcons.insert_line_16),
  const Icon(MoonIcons.insert_line_24),
  const Icon(MoonIcons.insert_line_32),
  const Icon(MoonIcons.italic_16),
  const Icon(MoonIcons.italic_24),
  const Icon(MoonIcons.italic_32),
  const Icon(MoonIcons.joystick_16),
  const Icon(MoonIcons.joystick_24),
  const Icon(MoonIcons.joystick_32),
  const Icon(MoonIcons.jpg_16),
  const Icon(MoonIcons.jpg_24),
  const Icon(MoonIcons.jpg_32),
  const Icon(MoonIcons.js_16),
  const Icon(MoonIcons.js_24),
  const Icon(MoonIcons.js_32),
  const Icon(MoonIcons.key_16),
  const Icon(MoonIcons.key_24),
  const Icon(MoonIcons.key_32),
  const Icon(MoonIcons.keyboard_16),
  const Icon(MoonIcons.keyboard_24),
  const Icon(MoonIcons.keyboard_32),
  const Icon(MoonIcons.keyboard_clear_16),
  const Icon(MoonIcons.keyboard_clear_24),
  const Icon(MoonIcons.keyboard_clear_32),
  const Icon(MoonIcons.left_16),
  const Icon(MoonIcons.left_24),
  const Icon(MoonIcons.left_32),
  const Icon(MoonIcons.left_align_16),
  const Icon(MoonIcons.left_align_24),
  const Icon(MoonIcons.left_align_32),
  const Icon(MoonIcons.left_curved_16),
  const Icon(MoonIcons.left_curved_24),
  const Icon(MoonIcons.left_curved_32),
  const Icon(MoonIcons.left_short_16),
  const Icon(MoonIcons.left_short_24),
  const Icon(MoonIcons.left_short_32),
  const Icon(MoonIcons.lifebuoy_16),
  const Icon(MoonIcons.lifebuoy_24),
  const Icon(MoonIcons.lifebuoy_32),
  const Icon(MoonIcons.lightning_16),
  const Icon(MoonIcons.lightning_24),
  const Icon(MoonIcons.lightning_32),
  const Icon(MoonIcons.lightning_bolt_16),
  const Icon(MoonIcons.lightning_bolt_24),
  const Icon(MoonIcons.lightning_bolt_32),
  const Icon(MoonIcons.like_16),
  const Icon(MoonIcons.like_24),
  const Icon(MoonIcons.like_32),
  const Icon(MoonIcons.line_16),
  const Icon(MoonIcons.line_24),
  const Icon(MoonIcons.line_32),
  const Icon(MoonIcons.line_chart_diagonal_16),
  const Icon(MoonIcons.line_chart_diagonal_24),
  const Icon(MoonIcons.line_chart_diagonal_32),
  const Icon(MoonIcons.link_16),
  const Icon(MoonIcons.link_24),
  const Icon(MoonIcons.link_32),
  const Icon(MoonIcons.list_view_16),
  const Icon(MoonIcons.list_view_24),
  const Icon(MoonIcons.list_view_32),
  const Icon(MoonIcons.live_casino_16),
  const Icon(MoonIcons.live_casino_24),
  const Icon(MoonIcons.live_casino_32),
  const Icon(MoonIcons.location_16),
  const Icon(MoonIcons.location_24),
  const Icon(MoonIcons.location_32),
  const Icon(MoonIcons.lock_16),
  const Icon(MoonIcons.lock_24),
  const Icon(MoonIcons.lock_32),
  const Icon(MoonIcons.log_in_16),
  const Icon(MoonIcons.log_in_24),
  const Icon(MoonIcons.log_in_32),
  const Icon(MoonIcons.log_out_16),
  const Icon(MoonIcons.log_out_24),
  const Icon(MoonIcons.log_out_32),
  const Icon(MoonIcons.loyalty_16),
  const Icon(MoonIcons.loyalty_24),
  const Icon(MoonIcons.loyalty_32),
  const Icon(MoonIcons.luggage_16),
  const Icon(MoonIcons.luggage_24),
  const Icon(MoonIcons.luggage_32),
  const Icon(MoonIcons.mac_16),
  const Icon(MoonIcons.mac_24),
  const Icon(MoonIcons.mac_32),
  const Icon(MoonIcons.macbook_16),
  const Icon(MoonIcons.macbook_24),
  const Icon(MoonIcons.macbook_32),
  const Icon(MoonIcons.macbook_and_iphone_16),
  const Icon(MoonIcons.macbook_and_iphone_24),
  const Icon(MoonIcons.macbook_and_iphone_32),
  const Icon(MoonIcons.magazine_16),
  const Icon(MoonIcons.magazine_24),
  const Icon(MoonIcons.magazine_32),
  const Icon(MoonIcons.magnet_16),
  const Icon(MoonIcons.magnet_24),
  const Icon(MoonIcons.magnet_32),
  const Icon(MoonIcons.map_16),
  const Icon(MoonIcons.map_24),
  const Icon(MoonIcons.map_32),
  const Icon(MoonIcons.marker_16),
  const Icon(MoonIcons.marker_24),
  const Icon(MoonIcons.marker_32),
  const Icon(MoonIcons.math_16),
  const Icon(MoonIcons.math_24),
  const Icon(MoonIcons.math_32),
  const Icon(MoonIcons.meal_16),
  const Icon(MoonIcons.meal_24),
  const Icon(MoonIcons.meal_32),
  const Icon(MoonIcons.megaphone_16),
  const Icon(MoonIcons.megaphone_24),
  const Icon(MoonIcons.megaphone_32),
  const Icon(MoonIcons.mention_16),
  const Icon(MoonIcons.mention_24),
  const Icon(MoonIcons.mention_32),
  const Icon(MoonIcons.menu_16),
  const Icon(MoonIcons.menu_24),
  const Icon(MoonIcons.menu_32),
  const Icon(MoonIcons.mice_16),
  const Icon(MoonIcons.mice_24),
  const Icon(MoonIcons.mice_32),
  const Icon(MoonIcons.mice_alternative_16),
  const Icon(MoonIcons.mice_alternative_24),
  const Icon(MoonIcons.mice_alternative_32),
  const Icon(MoonIcons.minus_16),
  const Icon(MoonIcons.minus_24),
  const Icon(MoonIcons.minus_32),
  const Icon(MoonIcons.minus_circular_16),
  const Icon(MoonIcons.minus_circular_24),
  const Icon(MoonIcons.minus_circular_32),
  const Icon(MoonIcons.monitor_16),
  const Icon(MoonIcons.monitor_24),
  const Icon(MoonIcons.monitor_32),
  const Icon(MoonIcons.moon_16),
  const Icon(MoonIcons.moon_24),
  const Icon(MoonIcons.moon_32),
  const Icon(MoonIcons.mouse_16),
  const Icon(MoonIcons.mouse_24),
  const Icon(MoonIcons.mouse_32),
  const Icon(MoonIcons.mp3_16),
  const Icon(MoonIcons.mp3_24),
  const Icon(MoonIcons.mp3_32),
  const Icon(MoonIcons.mp4_16),
  const Icon(MoonIcons.mp4_24),
  const Icon(MoonIcons.mp4_32),
  const Icon(MoonIcons.multi_bet_16),
  const Icon(MoonIcons.multi_bet_24),
  const Icon(MoonIcons.multi_bet_32),
  const Icon(MoonIcons.music_16),
  const Icon(MoonIcons.music_24),
  const Icon(MoonIcons.music_32),
  const Icon(MoonIcons.news_16),
  const Icon(MoonIcons.news_24),
  const Icon(MoonIcons.news_32),
  const Icon(MoonIcons.no_suitcase_16),
  const Icon(MoonIcons.no_suitcase_24),
  const Icon(MoonIcons.no_suitcase_32),
  const Icon(MoonIcons.no_volume_16),
  const Icon(MoonIcons.no_volume_24),
  const Icon(MoonIcons.no_volume_32),
  const Icon(MoonIcons.notifications_16),
  const Icon(MoonIcons.notifications_24),
  const Icon(MoonIcons.notifications_32),
  const Icon(MoonIcons.numbers_list_16),
  const Icon(MoonIcons.numbers_list_24),
  const Icon(MoonIcons.numbers_list_32),
  const Icon(MoonIcons.nut_16),
  const Icon(MoonIcons.nut_24),
  const Icon(MoonIcons.nut_32),
  const Icon(MoonIcons.panorama_16),
  const Icon(MoonIcons.panorama_24),
  const Icon(MoonIcons.panorama_32),
  const Icon(MoonIcons.partners_16),
  const Icon(MoonIcons.partners_24),
  const Icon(MoonIcons.partners_32),
  const Icon(MoonIcons.passport_16),
  const Icon(MoonIcons.passport_24),
  const Icon(MoonIcons.passport_32),
  const Icon(MoonIcons.passport_alert_16),
  const Icon(MoonIcons.passport_alert_24),
  const Icon(MoonIcons.passport_alert_32),
  const Icon(MoonIcons.pause_16),
  const Icon(MoonIcons.pause_24),
  const Icon(MoonIcons.pause_32),
  const Icon(MoonIcons.pending_16),
  const Icon(MoonIcons.pending_24),
  const Icon(MoonIcons.pending_32),
  const Icon(MoonIcons.phone_16),
  const Icon(MoonIcons.phone_24),
  const Icon(MoonIcons.phone_32),
  const Icon(MoonIcons.photo_16),
  const Icon(MoonIcons.photo_24),
  const Icon(MoonIcons.photo_32),
  const Icon(MoonIcons.php_16),
  const Icon(MoonIcons.php_24),
  const Icon(MoonIcons.php_32),
  const Icon(MoonIcons.picture_16),
  const Icon(MoonIcons.picture_24),
  const Icon(MoonIcons.picture_32),
  const Icon(MoonIcons.pie_chart_16),
  const Icon(MoonIcons.pie_chart_24),
  const Icon(MoonIcons.pie_chart_32),
  const Icon(MoonIcons.pin_16),
  const Icon(MoonIcons.pin_24),
  const Icon(MoonIcons.pin_32),
  const Icon(MoonIcons.pin_add_16),
  const Icon(MoonIcons.pin_add_24),
  const Icon(MoonIcons.pin_add_32),
  const Icon(MoonIcons.pin_location_16),
  const Icon(MoonIcons.pin_location_24),
  const Icon(MoonIcons.pin_location_32),
  const Icon(MoonIcons.pin_marker_16),
  const Icon(MoonIcons.pin_marker_24),
  const Icon(MoonIcons.pin_marker_32),
  const Icon(MoonIcons.plate_16),
  const Icon(MoonIcons.plate_24),
  const Icon(MoonIcons.plate_32),
  const Icon(MoonIcons.play_16),
  const Icon(MoonIcons.play_24),
  const Icon(MoonIcons.play_32),
  const Icon(MoonIcons.plug_eur_16),
  const Icon(MoonIcons.plug_eur_24),
  const Icon(MoonIcons.plug_eur_32),
  const Icon(MoonIcons.plug_uk_16),
  const Icon(MoonIcons.plug_uk_24),
  const Icon(MoonIcons.plug_uk_32),
  const Icon(MoonIcons.plus_16),
  const Icon(MoonIcons.plus_24),
  const Icon(MoonIcons.plus_32),
  const Icon(MoonIcons.plus_circular_16),
  const Icon(MoonIcons.plus_circular_24),
  const Icon(MoonIcons.plus_circular_32),
  const Icon(MoonIcons.png_16),
  const Icon(MoonIcons.png_24),
  const Icon(MoonIcons.png_32),
  const Icon(MoonIcons.ppt_16),
  const Icon(MoonIcons.ppt_24),
  const Icon(MoonIcons.ppt_32),
  const Icon(MoonIcons.print_16),
  const Icon(MoonIcons.print_24),
  const Icon(MoonIcons.print_32),
  const Icon(MoonIcons.psd_16),
  const Icon(MoonIcons.psd_24),
  const Icon(MoonIcons.psd_32),
  const Icon(MoonIcons.puzzle_16),
  const Icon(MoonIcons.puzzle_24),
  const Icon(MoonIcons.puzzle_32),
  const Icon(MoonIcons.qr_code_16),
  const Icon(MoonIcons.qr_code_24),
  const Icon(MoonIcons.qr_code_32),
  const Icon(MoonIcons.qr_code_alternative_16),
  const Icon(MoonIcons.qr_code_alternative_24),
  const Icon(MoonIcons.qr_code_alternative_32),
  const Icon(MoonIcons.question_mark_16),
  const Icon(MoonIcons.question_mark_24),
  const Icon(MoonIcons.question_mark_32),
  const Icon(MoonIcons.refresh_16),
  const Icon(MoonIcons.refresh_24),
  const Icon(MoonIcons.refresh_32),
  const Icon(MoonIcons.refresh_round_16),
  const Icon(MoonIcons.refresh_round_24),
  const Icon(MoonIcons.refresh_round_32),
  const Icon(MoonIcons.relation_16),
  const Icon(MoonIcons.relation_24),
  const Icon(MoonIcons.relation_32),
  const Icon(MoonIcons.remove_16),
  const Icon(MoonIcons.remove_24),
  const Icon(MoonIcons.remove_32),
  const Icon(MoonIcons.remove_boost_16),
  const Icon(MoonIcons.remove_boost_24),
  const Icon(MoonIcons.remove_boost_32),
  const Icon(MoonIcons.reply_16),
  const Icon(MoonIcons.reply_24),
  const Icon(MoonIcons.reply_32),
  const Icon(MoonIcons.rest_16),
  const Icon(MoonIcons.rest_24),
  const Icon(MoonIcons.rest_32),
  const Icon(MoonIcons.rewards_16),
  const Icon(MoonIcons.rewards_24),
  const Icon(MoonIcons.rewards_32),
  const Icon(MoonIcons.right_16),
  const Icon(MoonIcons.right_24),
  const Icon(MoonIcons.right_32),
  const Icon(MoonIcons.right_align_16),
  const Icon(MoonIcons.right_align_24),
  const Icon(MoonIcons.right_align_32),
  const Icon(MoonIcons.right_curved_16),
  const Icon(MoonIcons.right_curved_24),
  const Icon(MoonIcons.right_curved_32),
  const Icon(MoonIcons.right_left_arrow_16),
  const Icon(MoonIcons.right_left_arrow_24),
  const Icon(MoonIcons.right_left_arrow_32),
  const Icon(MoonIcons.right_short_16),
  const Icon(MoonIcons.right_short_24),
  const Icon(MoonIcons.right_short_32),
  const Icon(MoonIcons.rocket_16),
  const Icon(MoonIcons.rocket_24),
  const Icon(MoonIcons.rocket_32),
  const Icon(MoonIcons.room_16),
  const Icon(MoonIcons.room_24),
  const Icon(MoonIcons.room_32),
  const Icon(MoonIcons.round_16),
  const Icon(MoonIcons.round_24),
  const Icon(MoonIcons.round_32),
  const Icon(MoonIcons.sad_16),
  const Icon(MoonIcons.sad_24),
  const Icon(MoonIcons.sad_32),
  const Icon(MoonIcons.sandglass_16),
  const Icon(MoonIcons.sandglass_24),
  const Icon(MoonIcons.sandglass_32),
  const Icon(MoonIcons.save_16),
  const Icon(MoonIcons.save_24),
  const Icon(MoonIcons.save_32),
  const Icon(MoonIcons.scan_16),
  const Icon(MoonIcons.scan_24),
  const Icon(MoonIcons.scan_32),
  const Icon(MoonIcons.search_16),
  const Icon(MoonIcons.search_24),
  const Icon(MoonIcons.search_32),
  const Icon(MoonIcons.seats_16),
  const Icon(MoonIcons.seats_24),
  const Icon(MoonIcons.seats_32),
  const Icon(MoonIcons.security_attention_16),
  const Icon(MoonIcons.security_attention_24),
  const Icon(MoonIcons.security_attention_32),
  const Icon(MoonIcons.send_16),
  const Icon(MoonIcons.send_24),
  const Icon(MoonIcons.send_32),
  const Icon(MoonIcons.send_right_16),
  const Icon(MoonIcons.send_right_24),
  const Icon(MoonIcons.send_right_32),
  const Icon(MoonIcons.settings_16),
  const Icon(MoonIcons.settings_24),
  const Icon(MoonIcons.settings_32),
  const Icon(MoonIcons.settings_gear_16),
  const Icon(MoonIcons.settings_gear_24),
  const Icon(MoonIcons.settings_gear_32),
  const Icon(MoonIcons.share_16),
  const Icon(MoonIcons.share_24),
  const Icon(MoonIcons.share_32),
  const Icon(MoonIcons.share_android_16),
  const Icon(MoonIcons.share_android_24),
  const Icon(MoonIcons.share_android_32),
  const Icon(MoonIcons.share_arrow_16),
  const Icon(MoonIcons.share_arrow_24),
  const Icon(MoonIcons.share_arrow_32),
  const Icon(MoonIcons.share_ios_16),
  const Icon(MoonIcons.share_ios_24),
  const Icon(MoonIcons.share_ios_32),
  const Icon(MoonIcons.share_ios_big_16),
  const Icon(MoonIcons.share_ios_big_24),
  const Icon(MoonIcons.share_ios_big_32),
  const Icon(MoonIcons.shield_16),
  const Icon(MoonIcons.shield_24),
  const Icon(MoonIcons.shield_32),
  const Icon(MoonIcons.shield_secured_16),
  const Icon(MoonIcons.shield_secured_24),
  const Icon(MoonIcons.shield_secured_32),
  const Icon(MoonIcons.six_six_free_16),
  const Icon(MoonIcons.six_six_free_24),
  const Icon(MoonIcons.six_six_free_32),
  const Icon(MoonIcons.size_16),
  const Icon(MoonIcons.size_24),
  const Icon(MoonIcons.size_32),
  const Icon(MoonIcons.smartphone_16),
  const Icon(MoonIcons.smartphone_24),
  const Icon(MoonIcons.smartphone_32),
  const Icon(MoonIcons.smile_16),
  const Icon(MoonIcons.smile_24),
  const Icon(MoonIcons.smile_32),
  const Icon(MoonIcons.sorting_16),
  const Icon(MoonIcons.sorting_24),
  const Icon(MoonIcons.sorting_32),
  const Icon(MoonIcons.soundwave_16),
  const Icon(MoonIcons.soundwave_24),
  const Icon(MoonIcons.soundwave_32),
  const Icon(MoonIcons.speed_meter_16),
  const Icon(MoonIcons.speed_meter_24),
  const Icon(MoonIcons.speed_meter_32),
  const Icon(MoonIcons.star_16),
  const Icon(MoonIcons.star_24),
  const Icon(MoonIcons.star_32),
  const Icon(MoonIcons.stats_chat_16),
  const Icon(MoonIcons.stats_chat_24),
  const Icon(MoonIcons.stats_chat_32),
  const Icon(MoonIcons.sticker_16),
  const Icon(MoonIcons.sticker_24),
  const Icon(MoonIcons.sticker_32),
  const Icon(MoonIcons.stickers_16),
  const Icon(MoonIcons.stickers_24),
  const Icon(MoonIcons.stickers_32),
  const Icon(MoonIcons.stop_16),
  const Icon(MoonIcons.stop_24),
  const Icon(MoonIcons.stop_32),
  const Icon(MoonIcons.stopwatch_16),
  const Icon(MoonIcons.stopwatch_24),
  const Icon(MoonIcons.stopwatch_32),
  const Icon(MoonIcons.stopwatch_timer_16),
  const Icon(MoonIcons.stopwatch_timer_24),
  const Icon(MoonIcons.stopwatch_timer_32),
  const Icon(MoonIcons.strikethrough_16),
  const Icon(MoonIcons.strikethrough_24),
  const Icon(MoonIcons.strikethrough_32),
  const Icon(MoonIcons.style_16),
  const Icon(MoonIcons.style_24),
  const Icon(MoonIcons.style_32),
  const Icon(MoonIcons.suitcase_16),
  const Icon(MoonIcons.suitcase_24),
  const Icon(MoonIcons.suitcase_32),
  const Icon(MoonIcons.sun_16),
  const Icon(MoonIcons.sun_24),
  const Icon(MoonIcons.sun_32),
  const Icon(MoonIcons.swimming_pool_16),
  const Icon(MoonIcons.swimming_pool_24),
  const Icon(MoonIcons.swimming_pool_32),
  const Icon(MoonIcons.table_16),
  const Icon(MoonIcons.table_24),
  const Icon(MoonIcons.table_32),
  const Icon(MoonIcons.tag_16),
  const Icon(MoonIcons.tag_24),
  const Icon(MoonIcons.tag_32),
  const Icon(MoonIcons.text_16),
  const Icon(MoonIcons.text_24),
  const Icon(MoonIcons.text_32),
  const Icon(MoonIcons.three_dots_16),
  const Icon(MoonIcons.three_dots_24),
  const Icon(MoonIcons.three_dots_32),
  const Icon(MoonIcons.three_dots_horizontal_16),
  const Icon(MoonIcons.three_dots_horizontal_24),
  const Icon(MoonIcons.three_dots_horizontal_32),
  const Icon(MoonIcons.ticket_16),
  const Icon(MoonIcons.ticket_24),
  const Icon(MoonIcons.ticket_32),
  const Icon(MoonIcons.time_16),
  const Icon(MoonIcons.time_24),
  const Icon(MoonIcons.time_32),
  const Icon(MoonIcons.toggle_switch_16),
  const Icon(MoonIcons.toggle_switch_24),
  const Icon(MoonIcons.toggle_switch_32),
  const Icon(MoonIcons.top_left_16),
  const Icon(MoonIcons.top_left_24),
  const Icon(MoonIcons.top_left_32),
  const Icon(MoonIcons.top_right_16),
  const Icon(MoonIcons.top_right_24),
  const Icon(MoonIcons.top_right_32),
  const Icon(MoonIcons.trash_16),
  const Icon(MoonIcons.trash_24),
  const Icon(MoonIcons.trash_32),
  const Icon(MoonIcons.travel_pass_16),
  const Icon(MoonIcons.travel_pass_24),
  const Icon(MoonIcons.travel_pass_32),
  const Icon(MoonIcons.trophy_16),
  const Icon(MoonIcons.trophy_24),
  const Icon(MoonIcons.trophy_32),
  const Icon(MoonIcons.tuner_16),
  const Icon(MoonIcons.tuner_24),
  const Icon(MoonIcons.tuner_32),
  const Icon(MoonIcons.tuner_alternative_16),
  const Icon(MoonIcons.tuner_alternative_24),
  const Icon(MoonIcons.tuner_alternative_32),
  const Icon(MoonIcons.turn_off_16),
  const Icon(MoonIcons.turn_off_24),
  const Icon(MoonIcons.turn_off_32),
  const Icon(MoonIcons.turn_on_16),
  const Icon(MoonIcons.turn_on_24),
  const Icon(MoonIcons.turn_on_32),
  const Icon(MoonIcons.tv_box_16),
  const Icon(MoonIcons.tv_box_24),
  const Icon(MoonIcons.tv_box_32),
  const Icon(MoonIcons.txt_16),
  const Icon(MoonIcons.txt_24),
  const Icon(MoonIcons.txt_32),
  const Icon(MoonIcons.umbrella_16),
  const Icon(MoonIcons.umbrella_24),
  const Icon(MoonIcons.umbrella_32),
  const Icon(MoonIcons.underline_16),
  const Icon(MoonIcons.underline_24),
  const Icon(MoonIcons.underline_32),
  const Icon(MoonIcons.unlock_16),
  const Icon(MoonIcons.unlock_24),
  const Icon(MoonIcons.unlock_32),
  const Icon(MoonIcons.up_16),
  const Icon(MoonIcons.up_24),
  const Icon(MoonIcons.up_32),
  const Icon(MoonIcons.update_16),
  const Icon(MoonIcons.update_24),
  const Icon(MoonIcons.update_32),
  const Icon(MoonIcons.upload_16),
  const Icon(MoonIcons.upload_24),
  const Icon(MoonIcons.upload_32),
  const Icon(MoonIcons.upward_downward_arrow_16),
  const Icon(MoonIcons.upward_downward_arrow_24),
  const Icon(MoonIcons.upward_downward_arrow_32),
  const Icon(MoonIcons.user_16),
  const Icon(MoonIcons.user_24),
  const Icon(MoonIcons.user_32),
  const Icon(MoonIcons.user_swapping_16),
  const Icon(MoonIcons.user_swapping_24),
  const Icon(MoonIcons.user_swapping_32),
  const Icon(MoonIcons.users_16),
  const Icon(MoonIcons.users_24),
  const Icon(MoonIcons.users_32),
  const Icon(MoonIcons.verified_16),
  const Icon(MoonIcons.verified_24),
  const Icon(MoonIcons.verified_32),
  const Icon(MoonIcons.verified_face_16),
  const Icon(MoonIcons.verified_face_24),
  const Icon(MoonIcons.verified_face_32),
  const Icon(MoonIcons.vertical_double_chevron_16),
  const Icon(MoonIcons.vertical_double_chevron_24),
  const Icon(MoonIcons.vertical_double_chevron_32),
  const Icon(MoonIcons.video_16),
  const Icon(MoonIcons.video_24),
  const Icon(MoonIcons.video_32),
  const Icon(MoonIcons.volume_16),
  const Icon(MoonIcons.volume_24),
  const Icon(MoonIcons.volume_32),
  const Icon(MoonIcons.wallet_16),
  const Icon(MoonIcons.wallet_24),
  const Icon(MoonIcons.wallet_32),
  const Icon(MoonIcons.warning_16),
  const Icon(MoonIcons.warning_24),
  const Icon(MoonIcons.warning_32),
  const Icon(MoonIcons.watch_16),
  const Icon(MoonIcons.watch_24),
  const Icon(MoonIcons.watch_32),
  const Icon(MoonIcons.water_16),
  const Icon(MoonIcons.water_24),
  const Icon(MoonIcons.water_32),
  const Icon(MoonIcons.wi_fi_16),
  const Icon(MoonIcons.wi_fi_24),
  const Icon(MoonIcons.wi_fi_32),
  const Icon(MoonIcons.wireless_pay_16),
  const Icon(MoonIcons.wireless_pay_24),
  const Icon(MoonIcons.wireless_pay_32),
  const Icon(MoonIcons.world_16),
  const Icon(MoonIcons.world_24),
  const Icon(MoonIcons.world_32),
  const Icon(MoonIcons.wrench_16),
  const Icon(MoonIcons.wrench_24),
  const Icon(MoonIcons.wrench_32),
  const Icon(MoonIcons.xll_16),
  const Icon(MoonIcons.xll_24),
  const Icon(MoonIcons.xll_32),
  const Icon(MoonIcons.xml_16),
  const Icon(MoonIcons.xml_24),
  const Icon(MoonIcons.xml_32),
  const Icon(MoonIcons.yacht_16),
  const Icon(MoonIcons.yacht_24),
  const Icon(MoonIcons.yacht_32),
  const Icon(MoonIcons.zip_16),
  const Icon(MoonIcons.zip_24),
  const Icon(MoonIcons.zip_32),
  const Icon(MoonIcons.afl_32),
  const Icon(MoonIcons.american_football_32),
  const Icon(MoonIcons.archery_32),
  const Icon(MoonIcons.athletics_32),
  const Icon(MoonIcons.audl_32),
  const Icon(MoonIcons.badminton_32),
  const Icon(MoonIcons.baseball_32),
  const Icon(MoonIcons.basketball_32),
  const Icon(MoonIcons.beach_volleyball_32),
  const Icon(MoonIcons.biathlon_32),
  const Icon(MoonIcons.bombay_32),
  const Icon(MoonIcons.bowls_32),
  const Icon(MoonIcons.boxing_32),
  const Icon(MoonIcons.call_of_duty_32),
  const Icon(MoonIcons.canoeing_32),
  const Icon(MoonIcons.car_racing_32),
  const Icon(MoonIcons.casino_32),
  const Icon(MoonIcons.chess_32),
  const Icon(MoonIcons.cricket_32),
  const Icon(MoonIcons.cross_country_32),
  const Icon(MoonIcons.cs_go_32),
  const Icon(MoonIcons.curling_32),
  const Icon(MoonIcons.cycling_32),
  const Icon(MoonIcons.darts_32),
  const Icon(MoonIcons.diving_32),
  const Icon(MoonIcons.dota_2_32),
  const Icon(MoonIcons.e_ice_hockey_32),
  const Icon(MoonIcons.enba_32),
  const Icon(MoonIcons.equestrian_32),
  const Icon(MoonIcons.esoccer_32),
  const Icon(MoonIcons.esport_generic_32),
  const Icon(MoonIcons.featured_32),
  const Icon(MoonIcons.fencing_32),
  const Icon(MoonIcons.field_hockey_32),
  const Icon(MoonIcons.floorball_32),
  const Icon(MoonIcons.formula_1_32),
  const Icon(MoonIcons.formula_e_32),
  const Icon(MoonIcons.futsal_32),
  const Icon(MoonIcons.gaelic_hurling_32),
  const Icon(MoonIcons.golf_32),
  const Icon(MoonIcons.greyhound_32),
  const Icon(MoonIcons.gymnastics_32),
  const Icon(MoonIcons.handball_32),
  const Icon(MoonIcons.harness_32),
  const Icon(MoonIcons.horse_racing_32),
  const Icon(MoonIcons.ice_hockey_32),
  const Icon(MoonIcons.indy_racing_32),
  const Icon(MoonIcons.judo_32),
  const Icon(MoonIcons.kabaddi_32),
  const Icon(MoonIcons.king_of_glory_32),
  const Icon(MoonIcons.lacrosse_32),
  const Icon(MoonIcons.lol_32),
  const Icon(MoonIcons.mma_32),
  const Icon(MoonIcons.motor_32),
  const Icon(MoonIcons.motorcycle_racing_32),
  const Icon(MoonIcons.nordic_combined_32),
  const Icon(MoonIcons.olympics_32),
  const Icon(MoonIcons.overwatch_32),
  const Icon(MoonIcons.rainbow_six_32),
  const Icon(MoonIcons.rocket_league_32),
  const Icon(MoonIcons.rowing_32),
  const Icon(MoonIcons.rugby_32),
  const Icon(MoonIcons.sailing_32),
  const Icon(MoonIcons.set_tennis_32),
  const Icon(MoonIcons.skateboarding_32),
  const Icon(MoonIcons.ski_jumping_32),
  const Icon(MoonIcons.snooker_32),
  const Icon(MoonIcons.soccer_32),
  const Icon(MoonIcons.special_sports_32),
  const Icon(MoonIcons.specials_32),
  const Icon(MoonIcons.speedway_32),
  const Icon(MoonIcons.sportsbet_32),
  const Icon(MoonIcons.squash_32),
  const Icon(MoonIcons.surfing_32),
  const Icon(MoonIcons.swimming_32),
  const Icon(MoonIcons.table_tennis_32),
  const Icon(MoonIcons.tennis_32),
  const Icon(MoonIcons.triathlon_32),
  const Icon(MoonIcons.volleyball_32),
  const Icon(MoonIcons.waterpolo_32),
  const Icon(MoonIcons.weightlifting_32),
  const Icon(MoonIcons.wrestling_32),
];

final List<String> iconsNameList = [
  "about_16",
  "about_24",
  "about_32",
  "activity_16",
  "activity_24",
  "activity_32",
  "add_16",
  "add_24",
  "add_32",
  "add_bell_16",
  "add_bell_24",
  "add_bell_32",
  "add_text_16",
  "add_text_24",
  "add_text_32",
  "airplane_16",
  "airplane_24",
  "airplane_32",
  "airplane_down_16",
  "airplane_down_24",
  "airplane_down_32",
  "airplane_up_16",
  "airplane_up_24",
  "airplane_up_32",
  "alarm_round_16",
  "alarm_round_24",
  "alarm_round_32",
  "alert_16",
  "alert_24",
  "alert_32",
  "all_16",
  "all_24",
  "all_32",
  "anchor_16",
  "anchor_24",
  "anchor_32",
  "app_16",
  "app_24",
  "app_32",
  "area_16",
  "area_24",
  "area_32",
  "attach_16",
  "attach_24",
  "attach_32",
  "auto_play_16",
  "auto_play_24",
  "auto_play_32",
  "bag_16",
  "bag_24",
  "bag_32",
  "bank_16",
  "bank_24",
  "bank_32",
  "bar_16",
  "bar_24",
  "bar_32",
  "bar_alternative_16",
  "bar_alternative_24",
  "bar_alternative_32",
  "bar_vertical_16",
  "bar_vertical_24",
  "bar_vertical_32",
  "basket_16",
  "basket_24",
  "basket_32",
  "beach_chair_16",
  "beach_chair_24",
  "beach_chair_32",
  "bed_16",
  "bed_24",
  "bed_32",
  "bell_16",
  "bell_24",
  "bell_32",
  "bell_alarm_16",
  "bell_alarm_24",
  "bell_alarm_32",
  "bell_cross_16",
  "bell_cross_24",
  "bell_cross_32",
  "bell_ringing_16",
  "bell_ringing_24",
  "bell_ringing_32",
  "bell_ringing_alternative_16",
  "bell_ringing_alternative_24",
  "bell_ringing_alternative_32",
  "bet_16",
  "bet_24",
  "bet_32",
  "bet_insurance_16",
  "bet_insurance_24",
  "bet_insurance_32",
  "betslip_16",
  "betslip_24",
  "betslip_32",
  "bill_16",
  "bill_24",
  "bill_32",
  "block_16",
  "block_24",
  "block_32",
  "bluetooth_16",
  "bluetooth_24",
  "bluetooth_32",
  "bold_16",
  "bold_24",
  "bold_32",
  "bookmark_16",
  "bookmark_24",
  "bookmark_32",
  "bookmark_alternative_16",
  "bookmark_alternative_24",
  "bookmark_alternative_32",
  "boost_16",
  "boost_24",
  "boost_32",
  "bottom_left_16",
  "bottom_left_24",
  "bottom_left_32",
  "bottom_right_16",
  "bottom_right_24",
  "bottom_right_32",
  "box_16",
  "box_24",
  "box_32",
  "browser_16",
  "browser_24",
  "browser_32",
  "bug_16",
  "bug_24",
  "bug_32",
  "bullets_list_16",
  "bullets_list_24",
  "bullets_list_32",
  "burger_regular_16",
  "burger_regular_24",
  "burger_regular_32",
  "burger_zig_16",
  "burger_zig_24",
  "burger_zig_32",
  "buy_crypto_16",
  "buy_crypto_24",
  "buy_crypto_32",
  "calendar_16",
  "calendar_24",
  "calendar_32",
  "calendar_add_16",
  "calendar_add_24",
  "calendar_add_32",
  "calendar_alternative_16",
  "calendar_alternative_24",
  "calendar_alternative_32",
  "calendar_date_16",
  "calendar_date_24",
  "calendar_date_32",
  "calendar_remove_16",
  "calendar_remove_24",
  "calendar_remove_32",
  "calendar_success_16",
  "calendar_success_24",
  "calendar_success_32",
  "card_16",
  "card_24",
  "card_32",
  "cards_16",
  "cards_24",
  "cards_32",
  "cart_16",
  "cart_24",
  "cart_32",
  "case_16",
  "case_24",
  "case_32",
  "center_16",
  "center_24",
  "center_32",
  "chat_16",
  "chat_24",
  "chat_32",
  "check_alternative_16",
  "check_alternative_24",
  "check_alternative_32",
  "check_rounded_16",
  "check_rounded_24",
  "check_rounded_32",
  "chevron_down_16",
  "chevron_down_24",
  "chevron_down_32",
  "chevron_down_double_16",
  "chevron_down_double_24",
  "chevron_down_double_32",
  "chevron_down_small_16",
  "chevron_down_small_24",
  "chevron_down_small_32",
  "chevron_left_16",
  "chevron_left_24",
  "chevron_left_32",
  "chevron_left_double_16",
  "chevron_left_double_24",
  "chevron_left_double_32",
  "chevron_left_small_16",
  "chevron_left_small_24",
  "chevron_left_small_32",
  "chevron_right_16",
  "chevron_right_24",
  "chevron_right_32",
  "chevron_right_double_16",
  "chevron_right_double_24",
  "chevron_right_double_32",
  "chevron_right_small_16",
  "chevron_right_small_24",
  "chevron_right_small_32",
  "chevron_up_16",
  "chevron_up_24",
  "chevron_up_32",
  "chevron_up_double_16",
  "chevron_up_double_24",
  "chevron_up_double_32",
  "chevron_up_small_16",
  "chevron_up_small_24",
  "chevron_up_small_32",
  "claps_16",
  "claps_24",
  "claps_32",
  "clear_16",
  "clear_24",
  "clear_32",
  "clear_formatting_16",
  "clear_formatting_24",
  "clear_formatting_32",
  "clipboard_16",
  "clipboard_24",
  "clipboard_32",
  "clipboard_text_16",
  "clipboard_text_24",
  "clipboard_text_32",
  "clock_16",
  "clock_24",
  "clock_32",
  "clock_alarm_16",
  "clock_alarm_24",
  "clock_alarm_32",
  "close_16",
  "close_24",
  "close_32",
  "close_circular_16",
  "close_circular_24",
  "close_circular_32",
  "close_small_16",
  "close_small_24",
  "close_small_32",
  "cloud_download_16",
  "cloud_download_24",
  "cloud_download_32",
  "code_16",
  "code_24",
  "code_32",
  "code_file_16",
  "code_file_24",
  "code_file_32",
  "coins_16",
  "coins_24",
  "coins_32",
  "collapse_16",
  "collapse_24",
  "collapse_32",
  "comment_16",
  "comment_24",
  "comment_32",
  "comment_add_16",
  "comment_add_24",
  "comment_add_32",
  "comment_bubble_16",
  "comment_bubble_24",
  "comment_bubble_32",
  "comment_bubble_alert_16",
  "comment_bubble_alert_24",
  "comment_bubble_alert_32",
  "comment_bubble_question_mark_16",
  "comment_bubble_question_mark_24",
  "comment_bubble_question_mark_32",
  "comment_remove_16",
  "comment_remove_24",
  "comment_remove_32",
  "comment_text_16",
  "comment_text_24",
  "comment_text_32",
  "compass_16",
  "compass_24",
  "compass_32",
  "copy_16",
  "copy_24",
  "copy_32",
  "cross_lines_16",
  "cross_lines_24",
  "cross_lines_32",
  "crown_16",
  "crown_24",
  "crown_32",
  "crypto_16",
  "crypto_24",
  "crypto_32",
  "crypto_coin_16",
  "crypto_coin_24",
  "crypto_coin_32",
  "css_16",
  "css_24",
  "css_32",
  "csv_16",
  "csv_24",
  "csv_32",
  "cursor_16",
  "cursor_24",
  "cursor_32",
  "cut_16",
  "cut_24",
  "cut_32",
  "data_16",
  "data_24",
  "data_32",
  "decrease_indent_16",
  "decrease_indent_24",
  "decrease_indent_32",
  "delete_16",
  "delete_24",
  "delete_32",
  "desk_bell_16",
  "desk_bell_24",
  "desk_bell_32",
  "diagonals_bltr_16",
  "diagonals_bltr_24",
  "diagonals_bltr_32",
  "diagonals_insight_16",
  "diagonals_insight_24",
  "diagonals_insight_32",
  "diagonals_outsight_16",
  "diagonals_outsight_24",
  "diagonals_outsight_32",
  "diagonals_tlbr_16",
  "diagonals_tlbr_24",
  "diagonals_tlbr_32",
  "dislike_16",
  "dislike_24",
  "dislike_32",
  "double_bubble_16",
  "double_bubble_24",
  "double_bubble_32",
  "down_16",
  "down_24",
  "down_32",
  "download_16",
  "download_24",
  "download_32",
  "draft_16",
  "draft_24",
  "draft_32",
  "drag_handle_16",
  "drag_handle_24",
  "drag_handle_32",
  "edit_16",
  "edit_24",
  "edit_32",
  "email_stats_16",
  "email_stats_24",
  "email_stats_32",
  "envelope_16",
  "envelope_24",
  "envelope_32",
  "error_16",
  "error_24",
  "error_32",
  "exe_16",
  "exe_24",
  "exe_32",
  "expand_16",
  "expand_24",
  "expand_32",
  "expand_alt_16",
  "expand_alt_24",
  "expand_alt_32",
  "expand_rows_16",
  "expand_rows_24",
  "expand_rows_32",
  "export_16",
  "export_24",
  "export_32",
  "external_link_16",
  "external_link_24",
  "external_link_32",
  "eye_16",
  "eye_24",
  "eye_32",
  "eye_crossed_16",
  "eye_crossed_24",
  "eye_crossed_32",
  "fast_back_16",
  "fast_back_24",
  "fast_back_32",
  "fast_forward_16",
  "fast_forward_24",
  "fast_forward_32",
  "file_16",
  "file_24",
  "file_32",
  "file_table_16",
  "file_table_24",
  "file_table_32",
  "filter_16",
  "filter_24",
  "filter_32",
  "filter_crossed_16",
  "filter_crossed_24",
  "filter_crossed_32",
  "fin_16",
  "fin_24",
  "fin_32",
  "flag_16",
  "flag_24",
  "flag_32",
  "flame_16",
  "flame_24",
  "flame_32",
  "folder_closed_16",
  "folder_closed_24",
  "folder_closed_32",
  "folder_open_16",
  "folder_open_24",
  "folder_open_32",
  "folder_open_alternative_16",
  "folder_open_alternative_24",
  "folder_open_alternative_32",
  "folder_zip_16",
  "folder_zip_24",
  "folder_zip_32",
  "forward_16",
  "forward_24",
  "forward_32",
  "four_three_free_16",
  "four_three_free_24",
  "four_three_free_32",
  "frame_16",
  "frame_24",
  "frame_32",
  "freebet_16",
  "freebet_24",
  "freebet_32",
  "full_screen_16",
  "full_screen_24",
  "full_screen_32",
  "full_screen_out_16",
  "full_screen_out_24",
  "full_screen_out_32",
  "gif_alternative_16",
  "gif_alternative_24",
  "gif_alternative_32",
  "glasses_16",
  "glasses_24",
  "glasses_32",
  "globe_16",
  "globe_24",
  "globe_32",
  "hand_16",
  "hand_24",
  "hand_32",
  "hashtag_16",
  "hashtag_24",
  "hashtag_32",
  "headphones_16",
  "headphones_24",
  "headphones_32",
  "heart_16",
  "heart_24",
  "heart_32",
  "help_16",
  "help_24",
  "help_32",
  "home_16",
  "home_24",
  "home_32",
  "hotel_16",
  "hotel_24",
  "hotel_32",
  "html_16",
  "html_24",
  "html_32",
  "hyperlink_16",
  "hyperlink_24",
  "hyperlink_32",
  "id_16",
  "id_24",
  "id_32",
  "idea_16",
  "idea_24",
  "idea_32",
  "import_16",
  "import_24",
  "import_32",
  "increase_indent_16",
  "increase_indent_24",
  "increase_indent_32",
  "info_16",
  "info_24",
  "info_32",
  "info_alternative_16",
  "info_alternative_24",
  "info_alternative_32",
  "insert_line_16",
  "insert_line_24",
  "insert_line_32",
  "italic_16",
  "italic_24",
  "italic_32",
  "joystick_16",
  "joystick_24",
  "joystick_32",
  "jpg_16",
  "jpg_24",
  "jpg_32",
  "js_16",
  "js_24",
  "js_32",
  "key_16",
  "key_24",
  "key_32",
  "keyboard_16",
  "keyboard_24",
  "keyboard_32",
  "keyboard_clear_16",
  "keyboard_clear_24",
  "keyboard_clear_32",
  "left_16",
  "left_24",
  "left_32",
  "left_align_16",
  "left_align_24",
  "left_align_32",
  "left_curved_16",
  "left_curved_24",
  "left_curved_32",
  "left_short_16",
  "left_short_24",
  "left_short_32",
  "lifebuoy_16",
  "lifebuoy_24",
  "lifebuoy_32",
  "lightning_16",
  "lightning_24",
  "lightning_32",
  "lightning_bolt_16",
  "lightning_bolt_24",
  "lightning_bolt_32",
  "like_16",
  "like_24",
  "like_32",
  "line_16",
  "line_24",
  "line_32",
  "line_chart_diagonal_16",
  "line_chart_diagonal_24",
  "line_chart_diagonal_32",
  "link_16",
  "link_24",
  "link_32",
  "list_view_16",
  "list_view_24",
  "list_view_32",
  "live_casino_16",
  "live_casino_24",
  "live_casino_32",
  "location_16",
  "location_24",
  "location_32",
  "lock_16",
  "lock_24",
  "lock_32",
  "log_in_16",
  "log_in_24",
  "log_in_32",
  "log_out_16",
  "log_out_24",
  "log_out_32",
  "loyalty_16",
  "loyalty_24",
  "loyalty_32",
  "luggage_16",
  "luggage_24",
  "luggage_32",
  "mac_16",
  "mac_24",
  "mac_32",
  "macbook_16",
  "macbook_24",
  "macbook_32",
  "macbook_and_iphone_16",
  "macbook_and_iphone_24",
  "macbook_and_iphone_32",
  "magazine_16",
  "magazine_24",
  "magazine_32",
  "magnet_16",
  "magnet_24",
  "magnet_32",
  "map_16",
  "map_24",
  "map_32",
  "marker_16",
  "marker_24",
  "marker_32",
  "math_16",
  "math_24",
  "math_32",
  "meal_16",
  "meal_24",
  "meal_32",
  "megaphone_16",
  "megaphone_24",
  "megaphone_32",
  "mention_16",
  "mention_24",
  "mention_32",
  "menu_16",
  "menu_24",
  "menu_32",
  "mice_16",
  "mice_24",
  "mice_32",
  "mice_alternative_16",
  "mice_alternative_24",
  "mice_alternative_32",
  "minus_16",
  "minus_24",
  "minus_32",
  "minus_circular_16",
  "minus_circular_24",
  "minus_circular_32",
  "monitor_16",
  "monitor_24",
  "monitor_32",
  "moon_16",
  "moon_24",
  "moon_32",
  "mouse_16",
  "mouse_24",
  "mouse_32",
  "mp3_16",
  "mp3_24",
  "mp3_32",
  "mp4_16",
  "mp4_24",
  "mp4_32",
  "multi_bet_16",
  "multi_bet_24",
  "multi_bet_32",
  "music_16",
  "music_24",
  "music_32",
  "news_16",
  "news_24",
  "news_32",
  "no_suitcase_16",
  "no_suitcase_24",
  "no_suitcase_32",
  "no_volume_16",
  "no_volume_24",
  "no_volume_32",
  "notifications_16",
  "notifications_24",
  "notifications_32",
  "numbers_list_16",
  "numbers_list_24",
  "numbers_list_32",
  "nut_16",
  "nut_24",
  "nut_32",
  "panorama_16",
  "panorama_24",
  "panorama_32",
  "partners_16",
  "partners_24",
  "partners_32",
  "passport_16",
  "passport_24",
  "passport_32",
  "passport_alert_16",
  "passport_alert_24",
  "passport_alert_32",
  "pause_16",
  "pause_24",
  "pause_32",
  "pending_16",
  "pending_24",
  "pending_32",
  "phone_16",
  "phone_24",
  "phone_32",
  "photo_16",
  "photo_24",
  "photo_32",
  "php_16",
  "php_24",
  "php_32",
  "picture_16",
  "picture_24",
  "picture_32",
  "pie_chart_16",
  "pie_chart_24",
  "pie_chart_32",
  "pin_16",
  "pin_24",
  "pin_32",
  "pin_add_16",
  "pin_add_24",
  "pin_add_32",
  "pin_location_16",
  "pin_location_24",
  "pin_location_32",
  "pin_marker_16",
  "pin_marker_24",
  "pin_marker_32",
  "plate_16",
  "plate_24",
  "plate_32",
  "play_16",
  "play_24",
  "play_32",
  "plug_eur_16",
  "plug_eur_24",
  "plug_eur_32",
  "plug_uk_16",
  "plug_uk_24",
  "plug_uk_32",
  "plus_16",
  "plus_24",
  "plus_32",
  "plus_circular_16",
  "plus_circular_24",
  "plus_circular_32",
  "png_16",
  "png_24",
  "png_32",
  "ppt_16",
  "ppt_24",
  "ppt_32",
  "print_16",
  "print_24",
  "print_32",
  "psd_16",
  "psd_24",
  "psd_32",
  "puzzle_16",
  "puzzle_24",
  "puzzle_32",
  "qr_code_16",
  "qr_code_24",
  "qr_code_32",
  "qr_code_alternative_16",
  "qr_code_alternative_24",
  "qr_code_alternative_32",
  "question_mark_16",
  "question_mark_24",
  "question_mark_32",
  "refresh_16",
  "refresh_24",
  "refresh_32",
  "refresh_round_16",
  "refresh_round_24",
  "refresh_round_32",
  "relation_16",
  "relation_24",
  "relation_32",
  "remove_16",
  "remove_24",
  "remove_32",
  "remove_boost_16",
  "remove_boost_24",
  "remove_boost_32",
  "reply_16",
  "reply_24",
  "reply_32",
  "rest_16",
  "rest_24",
  "rest_32",
  "rewards_16",
  "rewards_24",
  "rewards_32",
  "right_16",
  "right_24",
  "right_32",
  "right_align_16",
  "right_align_24",
  "right_align_32",
  "right_curved_16",
  "right_curved_24",
  "right_curved_32",
  "right_left_arrow_16",
  "right_left_arrow_24",
  "right_left_arrow_32",
  "right_short_16",
  "right_short_24",
  "right_short_32",
  "rocket_16",
  "rocket_24",
  "rocket_32",
  "room_16",
  "room_24",
  "room_32",
  "round_16",
  "round_24",
  "round_32",
  "sad_16",
  "sad_24",
  "sad_32",
  "sandglass_16",
  "sandglass_24",
  "sandglass_32",
  "save_16",
  "save_24",
  "save_32",
  "scan_16",
  "scan_24",
  "scan_32",
  "search_16",
  "search_24",
  "search_32",
  "seats_16",
  "seats_24",
  "seats_32",
  "security_attention_16",
  "security_attention_24",
  "security_attention_32",
  "send_16",
  "send_24",
  "send_32",
  "send_right_16",
  "send_right_24",
  "send_right_32",
  "settings_16",
  "settings_24",
  "settings_32",
  "settings_gear_16",
  "settings_gear_24",
  "settings_gear_32",
  "share_16",
  "share_24",
  "share_32",
  "share_android_16",
  "share_android_24",
  "share_android_32",
  "share_arrow_16",
  "share_arrow_24",
  "share_arrow_32",
  "share_ios_16",
  "share_ios_24",
  "share_ios_32",
  "share_ios_big_16",
  "share_ios_big_24",
  "share_ios_big_32",
  "shield_16",
  "shield_24",
  "shield_32",
  "shield_secured_16",
  "shield_secured_24",
  "shield_secured_32",
  "six_six_free_16",
  "six_six_free_24",
  "six_six_free_32",
  "size_16",
  "size_24",
  "size_32",
  "smartphone_16",
  "smartphone_24",
  "smartphone_32",
  "smile_16",
  "smile_24",
  "smile_32",
  "sorting_16",
  "sorting_24",
  "sorting_32",
  "soundwave_16",
  "soundwave_24",
  "soundwave_32",
  "speed_meter_16",
  "speed_meter_24",
  "speed_meter_32",
  "star_16",
  "star_24",
  "star_32",
  "stats_chat_16",
  "stats_chat_24",
  "stats_chat_32",
  "sticker_16",
  "sticker_24",
  "sticker_32",
  "stickers_16",
  "stickers_24",
  "stickers_32",
  "stop_16",
  "stop_24",
  "stop_32",
  "stopwatch_16",
  "stopwatch_24",
  "stopwatch_32",
  "stopwatch_timer_16",
  "stopwatch_timer_24",
  "stopwatch_timer_32",
  "strikethrough_16",
  "strikethrough_24",
  "strikethrough_32",
  "style_16",
  "style_24",
  "style_32",
  "suitcase_16",
  "suitcase_24",
  "suitcase_32",
  "sun_16",
  "sun_24",
  "sun_32",
  "swimming_pool_16",
  "swimming_pool_24",
  "swimming_pool_32",
  "table_16",
  "table_24",
  "table_32",
  "tag_16",
  "tag_24",
  "tag_32",
  "text_16",
  "text_24",
  "text_32",
  "three_dots_16",
  "three_dots_24",
  "three_dots_32",
  "three_dots_horizontal_16",
  "three_dots_horizontal_24",
  "three_dots_horizontal_32",
  "ticket_16",
  "ticket_24",
  "ticket_32",
  "time_16",
  "time_24",
  "time_32",
  "toggle_switch_16",
  "toggle_switch_24",
  "toggle_switch_32",
  "top_left_16",
  "top_left_24",
  "top_left_32",
  "top_right_16",
  "top_right_24",
  "top_right_32",
  "trash_16",
  "trash_24",
  "trash_32",
  "travel_pass_16",
  "travel_pass_24",
  "travel_pass_32",
  "trophy_16",
  "trophy_24",
  "trophy_32",
  "tuner_16",
  "tuner_24",
  "tuner_32",
  "tuner_alternative_16",
  "tuner_alternative_24",
  "tuner_alternative_32",
  "turn_off_16",
  "turn_off_24",
  "turn_off_32",
  "turn_on_16",
  "turn_on_24",
  "turn_on_32",
  "tv_box_16",
  "tv_box_24",
  "tv_box_32",
  "txt_16",
  "txt_24",
  "txt_32",
  "umbrella_16",
  "umbrella_24",
  "umbrella_32",
  "underline_16",
  "underline_24",
  "underline_32",
  "unlock_16",
  "unlock_24",
  "unlock_32",
  "up_16",
  "up_24",
  "up_32",
  "update_16",
  "update_24",
  "update_32",
  "upload_16",
  "upload_24",
  "upload_32",
  "upward_downward_arrow_16",
  "upward_downward_arrow_24",
  "upward_downward_arrow_32",
  "user_16",
  "user_24",
  "user_32",
  "user_swapping_16",
  "user_swapping_24",
  "user_swapping_32",
  "users_16",
  "users_24",
  "users_32",
  "verified_16",
  "verified_24",
  "verified_32",
  "verified_face_16",
  "verified_face_24",
  "verified_face_32",
  "vertical_double_chevron_16",
  "vertical_double_chevron_24",
  "vertical_double_chevron_32",
  "video_16",
  "video_24",
  "video_32",
  "volume_16",
  "volume_24",
  "volume_32",
  "wallet_16",
  "wallet_24",
  "wallet_32",
  "warning_16",
  "warning_24",
  "warning_32",
  "watch_16",
  "watch_24",
  "watch_32",
  "water_16",
  "water_24",
  "water_32",
  "wi_fi_16",
  "wi_fi_24",
  "wi_fi_32",
  "wireless_pay_16",
  "wireless_pay_24",
  "wireless_pay_32",
  "world_16",
  "world_24",
  "world_32",
  "wrench_16",
  "wrench_24",
  "wrench_32",
  "xll_16",
  "xll_24",
  "xll_32",
  "xml_16",
  "xml_24",
  "xml_32",
  "yacht_16",
  "yacht_24",
  "yacht_32",
  "zip_16",
  "zip_24",
  "zip_32",
  "afl_32",
  "american_football_32",
  "archery_32",
  "athletics_32",
  "audl_32",
  "badminton_32",
  "baseball_32",
  "basketball_32",
  "beach_volleyball_32",
  "biathlon_32",
  "bombay_32",
  "bowls_32",
  "boxing_32",
  "call_of_duty_32",
  "canoeing_32",
  "car_racing_32",
  "casino_32",
  "chess_32",
  "cricket_32",
  "cross_country_32",
  "cs_go_32",
  "curling_32",
  "cycling_32",
  "darts_32",
  "diving_32",
  "dota_2_32",
  "e_ice_hockey_32",
  "enba_32",
  "equestrian_32",
  "esoccer_32",
  "esport_generic_32",
  "featured_32",
  "fencing_32",
  "field_hockey_32",
  "floorball_32",
  "formula_1_32",
  "formula_e_32",
  "futsal_32",
  "gaelic_hurling_32",
  "golf_32",
  "greyhound_32",
  "gymnastics_32",
  "handball_32",
  "harness_32",
  "horse_racing_32",
  "ice_hockey_32",
  "indy_racing_32",
  "judo_32",
  "kabaddi_32",
  "king_of_glory_32",
  "lacrosse_32",
  "lol_32",
  "mma_32",
  "motor_32",
  "motorcycle_racing_32",
  "nordic_combined_32",
  "olympics_32",
  "overwatch_32",
  "rainbow_six_32",
  "rocket_league_32",
  "rowing_32",
  "rugby_32",
  "sailing_32",
  "set_tennis_32",
  "skateboarding_32",
  "ski_jumping_32",
  "snooker_32",
  "soccer_32",
  "special_sports_32",
  "specials_32",
  "speedway_32",
  "sportsbet_32",
  "squash_32",
  "surfing_32",
  "swimming_32",
  "table_tennis_32",
  "tennis_32",
  "triathlon_32",
  "volleyball_32",
  "waterpolo_32",
  "weightlifting_32",
  "wrestling_32",
];
