import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsFilesList = [
  const Icon(MoonIconsFiles.add_text16),
  const Icon(MoonIconsFiles.add_text24),
  const Icon(MoonIconsFiles.add_text32),
  const Icon(MoonIconsFiles.add16),
  const Icon(MoonIconsFiles.add24),
  const Icon(MoonIconsFiles.add32),
  const Icon(MoonIconsFiles.case16),
  const Icon(MoonIconsFiles.case24),
  const Icon(MoonIconsFiles.case32),
  const Icon(MoonIconsFiles.clipboard_text16),
  const Icon(MoonIconsFiles.clipboard_text24),
  const Icon(MoonIconsFiles.clipboard_text32),
  const Icon(MoonIconsFiles.clipboard16),
  const Icon(MoonIconsFiles.clipboard24),
  const Icon(MoonIconsFiles.clipboard32),
  const Icon(MoonIconsFiles.code16),
  const Icon(MoonIconsFiles.code24),
  const Icon(MoonIconsFiles.code32),
  const Icon(MoonIconsFiles.copy16),
  const Icon(MoonIconsFiles.copy24),
  const Icon(MoonIconsFiles.copy32),
  const Icon(MoonIconsFiles.delete16),
  const Icon(MoonIconsFiles.delete24),
  const Icon(MoonIconsFiles.delete32),
  const Icon(MoonIconsFiles.draft16),
  const Icon(MoonIconsFiles.draft24),
  const Icon(MoonIconsFiles.draft32),
  const Icon(MoonIconsFiles.export16),
  const Icon(MoonIconsFiles.export24),
  const Icon(MoonIconsFiles.export32),
  const Icon(MoonIconsFiles.external_link16),
  const Icon(MoonIconsFiles.external_link24),
  const Icon(MoonIconsFiles.external_link32),
  const Icon(MoonIconsFiles.file16),
  const Icon(MoonIconsFiles.file24),
  const Icon(MoonIconsFiles.file32),
  const Icon(MoonIconsFiles.folder_closed16),
  const Icon(MoonIconsFiles.folder_closed24),
  const Icon(MoonIconsFiles.folder_closed32),
  const Icon(MoonIconsFiles.folder_open_alternative16),
  const Icon(MoonIconsFiles.folder_open_alternative24),
  const Icon(MoonIconsFiles.folder_open_alternative32),
  const Icon(MoonIconsFiles.folder_open16),
  const Icon(MoonIconsFiles.folder_open24),
  const Icon(MoonIconsFiles.folder_open32),
  const Icon(MoonIconsFiles.folder_zip16),
  const Icon(MoonIconsFiles.folder_zip24),
  const Icon(MoonIconsFiles.folder_zip32),
  const Icon(MoonIconsFiles.glasses16),
  const Icon(MoonIconsFiles.glasses24),
  const Icon(MoonIconsFiles.glasses32),
  const Icon(MoonIconsFiles.import16),
  const Icon(MoonIconsFiles.import24),
  const Icon(MoonIconsFiles.import32),
  const Icon(MoonIconsFiles.magazine16),
  const Icon(MoonIconsFiles.magazine24),
  const Icon(MoonIconsFiles.magazine32),
  const Icon(MoonIconsFiles.print16),
  const Icon(MoonIconsFiles.print24),
  const Icon(MoonIconsFiles.print32),
  const Icon(MoonIconsFiles.remove16),
  const Icon(MoonIconsFiles.remove24),
  const Icon(MoonIconsFiles.remove32),
  const Icon(MoonIconsFiles.save16),
  const Icon(MoonIconsFiles.save24),
  const Icon(MoonIconsFiles.save32),
  const Icon(MoonIconsFiles.scan16),
  const Icon(MoonIconsFiles.scan24),
  const Icon(MoonIconsFiles.scan32),
  const Icon(MoonIconsFiles.share16),
  const Icon(MoonIconsFiles.share24),
  const Icon(MoonIconsFiles.share32),
  const Icon(MoonIconsFiles.sticker16),
  const Icon(MoonIconsFiles.sticker24),
  const Icon(MoonIconsFiles.sticker32),
  const Icon(MoonIconsFiles.stickers16),
  const Icon(MoonIconsFiles.stickers24),
  const Icon(MoonIconsFiles.stickers32),
  const Icon(MoonIconsFiles.table16),
  const Icon(MoonIconsFiles.table24),
  const Icon(MoonIconsFiles.table32),
  const Icon(MoonIconsFiles.text16),
  const Icon(MoonIconsFiles.text24),
  const Icon(MoonIconsFiles.text32),
];

final List<String> iconsFilesNameList = [
  "add_text16",
  "add_text24",
  "add_text32",
  "add16",
  "add24",
  "add32",
  "case16",
  "case24",
  "case32",
  "clipboard_text16",
  "clipboard_text24",
  "clipboard_text32",
  "clipboard16",
  "clipboard24",
  "clipboard32",
  "code16",
  "code24",
  "code32",
  "copy16",
  "copy24",
  "copy32",
  "delete16",
  "delete24",
  "delete32",
  "draft16",
  "draft24",
  "draft32",
  "export16",
  "export24",
  "export32",
  "external_link16",
  "external_link24",
  "external_link32",
  "file16",
  "file24",
  "file32",
  "folder_closed16",
  "folder_closed24",
  "folder_closed32",
  "folder_open_alternative16",
  "folder_open_alternative24",
  "folder_open_alternative32",
  "folder_open16",
  "folder_open24",
  "folder_open32",
  "folder_zip16",
  "folder_zip24",
  "folder_zip32",
  "glasses16",
  "glasses24",
  "glasses32",
  "import16",
  "import24",
  "import32",
  "magazine16",
  "magazine24",
  "magazine32",
  "print16",
  "print24",
  "print32",
  "remove16",
  "remove24",
  "remove32",
  "save16",
  "save24",
  "save32",
  "scan16",
  "scan24",
  "scan32",
  "share16",
  "share24",
  "share32",
  "sticker16",
  "sticker24",
  "sticker32",
  "stickers16",
  "stickers24",
  "stickers32",
  "table16",
  "table24",
  "table32",
  "text16",
  "text24",
  "text32",
];
