import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';

final List<Icon> iconsArrowsList = [
  const Icon(MoonIconsArrows.boost16),
  const Icon(MoonIconsArrows.boost24),
  const Icon(MoonIconsArrows.boost32),
  const Icon(MoonIconsArrows.bottom_left16),
  const Icon(MoonIconsArrows.bottom_left24),
  const Icon(MoonIconsArrows.bottom_left32),
  const Icon(MoonIconsArrows.bottom_right16),
  const Icon(MoonIconsArrows.bottom_right24),
  const Icon(MoonIconsArrows.bottom_right32),
  const Icon(MoonIconsArrows.chevron_down_double16),
  const Icon(MoonIconsArrows.chevron_down_double24),
  const Icon(MoonIconsArrows.chevron_down_double32),
  const Icon(MoonIconsArrows.chevron_left_double16),
  const Icon(MoonIconsArrows.chevron_left_double24),
  const Icon(MoonIconsArrows.chevron_left_double32),
  const Icon(MoonIconsArrows.chevron_right_double16),
  const Icon(MoonIconsArrows.chevron_right_double24),
  const Icon(MoonIconsArrows.chevron_right_double32),
  const Icon(MoonIconsArrows.chevron_up_double16),
  const Icon(MoonIconsArrows.chevron_up_double24),
  const Icon(MoonIconsArrows.chevron_up_double32),
  const Icon(MoonIconsArrows.cross_lines16),
  const Icon(MoonIconsArrows.cross_lines24),
  const Icon(MoonIconsArrows.cross_lines32),
  const Icon(MoonIconsArrows.diagonals_bltr16),
  const Icon(MoonIconsArrows.diagonals_bltr24),
  const Icon(MoonIconsArrows.diagonals_bltr32),
  const Icon(MoonIconsArrows.diagonals_tlbr16),
  const Icon(MoonIconsArrows.diagonals_tlbr24),
  const Icon(MoonIconsArrows.diagonals_tlbr32),
  const Icon(MoonIconsArrows.down16),
  const Icon(MoonIconsArrows.down24),
  const Icon(MoonIconsArrows.down32),
  const Icon(MoonIconsArrows.forward16),
  const Icon(MoonIconsArrows.forward24),
  const Icon(MoonIconsArrows.forward32),
  const Icon(MoonIconsArrows.left_curved16),
  const Icon(MoonIconsArrows.left_curved24),
  const Icon(MoonIconsArrows.left_curved32),
  const Icon(MoonIconsArrows.left_short16),
  const Icon(MoonIconsArrows.left_short24),
  const Icon(MoonIconsArrows.left_short32),
  const Icon(MoonIconsArrows.left16),
  const Icon(MoonIconsArrows.left24),
  const Icon(MoonIconsArrows.left32),
  const Icon(MoonIconsArrows.refresh_round16),
  const Icon(MoonIconsArrows.refresh_round24),
  const Icon(MoonIconsArrows.refresh_round32),
  const Icon(MoonIconsArrows.refresh16),
  const Icon(MoonIconsArrows.refresh24),
  const Icon(MoonIconsArrows.refresh32),
  const Icon(MoonIconsArrows.remove_boost16),
  const Icon(MoonIconsArrows.remove_boost24),
  const Icon(MoonIconsArrows.remove_boost32),
  const Icon(MoonIconsArrows.reply16),
  const Icon(MoonIconsArrows.reply24),
  const Icon(MoonIconsArrows.reply32),
  const Icon(MoonIconsArrows.right_curved16),
  const Icon(MoonIconsArrows.right_curved24),
  const Icon(MoonIconsArrows.right_curved32),
  const Icon(MoonIconsArrows.right_short16),
  const Icon(MoonIconsArrows.right_short24),
  const Icon(MoonIconsArrows.right_short32),
  const Icon(MoonIconsArrows.right16),
  const Icon(MoonIconsArrows.right24),
  const Icon(MoonIconsArrows.right32),
  const Icon(MoonIconsArrows.sorting16),
  const Icon(MoonIconsArrows.sorting24),
  const Icon(MoonIconsArrows.sorting32),
  const Icon(MoonIconsArrows.top_left16),
  const Icon(MoonIconsArrows.top_left24),
  const Icon(MoonIconsArrows.top_left32),
  const Icon(MoonIconsArrows.top_right16),
  const Icon(MoonIconsArrows.top_right24),
  const Icon(MoonIconsArrows.top_right32),
  const Icon(MoonIconsArrows.transfer16),
  const Icon(MoonIconsArrows.transfer24),
  const Icon(MoonIconsArrows.transfer32),
  const Icon(MoonIconsArrows.up16),
  const Icon(MoonIconsArrows.up24),
  const Icon(MoonIconsArrows.up32),
  const Icon(MoonIconsArrows.update16),
  const Icon(MoonIconsArrows.update24),
  const Icon(MoonIconsArrows.update32),
];

final List<String> iconsArrowsNameList = [
  "boost16",
  "boost24",
  "boost32",
  "bottom_left16",
  "bottom_left24",
  "bottom_left32",
  "bottom_right16",
  "bottom_right24",
  "bottom_right32",
  "chevron_down_double16",
  "chevron_down_double24",
  "chevron_down_double32",
  "chevron_left_double16",
  "chevron_left_double24",
  "chevron_left_double32",
  "chevron_right_double16",
  "chevron_right_double24",
  "chevron_right_double32",
  "chevron_up_double16",
  "chevron_up_double24",
  "chevron_up_double32",
  "cross_lines16",
  "cross_lines24",
  "cross_lines32",
  "diagonals_bltr16",
  "diagonals_bltr24",
  "diagonals_bltr32",
  "diagonals_tlbr16",
  "diagonals_tlbr24",
  "diagonals_tlbr32",
  "down16",
  "down24",
  "down32",
  "forward16",
  "forward24",
  "forward32",
  "left_curved16",
  "left_curved24",
  "left_curved32",
  "left_short16",
  "left_short24",
  "left_short32",
  "left16",
  "left24",
  "left32",
  "refresh_round16",
  "refresh_round24",
  "refresh_round32",
  "refresh16",
  "refresh24",
  "refresh32",
  "remove_boost16",
  "remove_boost24",
  "remove_boost32",
  "reply16",
  "reply24",
  "reply32",
  "right_curved16",
  "right_curved24",
  "right_curved32",
  "right_short16",
  "right_short24",
  "right_short32",
  "right16",
  "right24",
  "right32",
  "sorting16",
  "sorting24",
  "sorting32",
  "top_left16",
  "top_left24",
  "top_left32",
  "top_right16",
  "top_right24",
  "top_right32",
  "transfer16",
  "transfer24",
  "transfer32",
  "up16",
  "up24",
  "up32",
  "update16",
  "update24",
  "update32",
];
