import 'package:flutter/material.dart';
import 'package:moon_design/moon_design.dart';
import 'package:storybook_flutter/storybook_flutter.dart';

List<Option<Color>> colorOptions(BuildContext context) => [
      Option(label: "piccolo", value: context.moonColors!.piccolo),
      Option(label: "hit", value: context.moonColors!.hit),
      Option(label: "beerus", value: context.moonColors!.beerus),
      Option(label: "goku", value: context.moonColors!.goku),
      Option(label: "gohan", value: context.moonColors!.gohan),
      Option(label: "bulma", value: context.moonColors!.bulma),
      Option(label: "trunks", value: context.moonColors!.trunks),
      Option(label: "goten", value: context.moonColors!.goten),
      Option(label: "popo", value: context.moonColors!.popo),
      Option(label: "jiren", value: context.moonColors!.jiren),
      Option(label: "heles", value: context.moonColors!.heles),
      Option(label: "zeno", value: context.moonColors!.zeno),
      Option(label: "krillin100", value: context.moonColors!.krillin100),
      Option(label: "krillin60", value: context.moonColors!.krillin60),
      Option(label: "krillin10", value: context.moonColors!.krillin10),
      Option(label: "chichi100", value: context.moonColors!.chiChi100),
      Option(label: "chichi60", value: context.moonColors!.chiChi60),
      Option(label: "chichi10", value: context.moonColors!.chiChi10),
      Option(label: "roshi100", value: context.moonColors!.roshi60),
      Option(label: "roshi60", value: context.moonColors!.roshi100),
      Option(label: "roshi10", value: context.moonColors!.roshi10),
      Option(label: "frieza100", value: context.moonColors!.frieza100),
      Option(label: "frieza60", value: context.moonColors!.frieza60),
      Option(label: "frieza10", value: context.moonColors!.frieza10),
      Option(label: "dodoria100", value: context.moonColors!.dodoria100),
      Option(label: "dodoria60", value: context.moonColors!.dodoria60),
      Option(label: "dodoria10", value: context.moonColors!.dodoria10),
      Option(label: "cell100", value: context.moonColors!.cell100),
      Option(label: "cell60", value: context.moonColors!.cell60),
      Option(label: "cell10", value: context.moonColors!.cell10),
      Option(label: "raditz100", value: context.moonColors!.raditz100),
      Option(label: "raditz60", value: context.moonColors!.raditz60),
      Option(label: "raditz10", value: context.moonColors!.raditz10),
      Option(label: "nappa100", value: context.moonColors!.nappa100),
      Option(label: "nappa60", value: context.moonColors!.nappa60),
      Option(label: "nappa10", value: context.moonColors!.nappa10),
      Option(label: "whis100", value: context.moonColors!.whis100),
      Option(label: "whis60", value: context.moonColors!.whis60),
      Option(label: "whis10", value: context.moonColors!.whis10),
    ];
