name: Analyze and test (v2)
on:
  pull_request:
    branches:
      - v2
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./example

      - name: Run static analysis
        run: flutter analyze .

      - name: Run tests
        run: flutter test