name: Analyze and test
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
          channel: stable

      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./example

      - name: Run static analysis
        run: flutter analyze .

      - name: Run tests
        run: flutter test